module Increase
  module Resources
    class AccountTransfers
      private def initialize_resources: -> void

      def create: (
        account_id: String,
        amount: Integer,
        description: String,
        destination_account_id: String,
        ?require_approval: bool,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::AccountTransfer

      def retrieve: (
        String account_transfer_id,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::AccountTransfer

      def list: (
        ?account_id: String,
        ?created_at: Increase::Models::AccountTransferListParams::CreatedAt,
        ?cursor: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::Models::AccountTransfer]

      def approve: (
        String account_transfer_id,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::AccountTransfer

      def cancel: (
        String account_transfer_id,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::AccountTransfer

      def initialize: (client: Increase::Client) -> void
    end
  end
end
