module Increase
  module Resources
    class AccountTransfers
      def create: ((Increase::Models::AccountTransferCreateParams | ::Hash[Symbol, top]) params) -> Increase::Models::AccountTransfer
                | (account_id: String, amount: Integer, description: String, destination_account_id: String, require_approval: bool, request_options: Increase::request_opts) -> Increase::Models::AccountTransfer

      def retrieve: (String account_transfer_id, ?(Increase::Models::AccountTransferRetrieveParams | ::Hash[Symbol, top]) params) -> Increase::Models::AccountTransfer
                  | (String account_transfer_id, request_options: Increase::request_opts) -> Increase::Models::AccountTransfer

      def list: (?(Increase::Models::AccountTransferListParams | ::Hash[Symbol, top]) params) -> Increase::Page[Increase::Models::AccountTransfer]
              | (account_id: String, created_at: Increase::Models::AccountTransferListParams::CreatedAt, cursor: String, idempotency_key: String, limit: Integer, request_options: Increase::request_opts) -> Increase::Page[Increase::Models::AccountTransfer]

      def approve: (String account_transfer_id, ?(Increase::Models::AccountTransferApproveParams | ::Hash[Symbol, top]) params) -> Increase::Models::AccountTransfer
                 | (String account_transfer_id, request_options: Increase::request_opts) -> Increase::Models::AccountTransfer

      def cancel: (String account_transfer_id, ?(Increase::Models::AccountTransferCancelParams | ::Hash[Symbol, top]) params) -> Increase::Models::AccountTransfer
                | (String account_transfer_id, request_options: Increase::request_opts) -> Increase::Models::AccountTransfer

      def initialize: (client: Increase::Client) -> void
    end
  end
end
