module Increase
  module Resources
    class AccountStatements
      def retrieve: (
        String account_statement_id,
        ?request_options: Increase::request_opts
      ) -> Increase::AccountStatement

      def list: (
        ?account_id: String,
        ?cursor: String,
        ?limit: Integer,
        ?statement_period_start: Increase::AccountStatementListParams::StatementPeriodStart,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::AccountStatement]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
