module Increase
  module Resources
    class ACHTransfers
      def create: (
        account_id: String,
        amount: Integer,
        statement_descriptor: String,
        ?account_number: String,
        ?addenda: Increase::ACHTransferCreateParams::Addenda,
        ?company_descriptive_date: String,
        ?company_discretionary_data: String,
        ?company_entry_description: String,
        ?company_name: String,
        ?destination_account_holder: Increase::Models::ACHTransferCreateParams::destination_account_holder,
        ?external_account_id: String,
        ?funding: Increase::Models::ACHTransferCreateParams::funding,
        ?individual_id: String,
        ?individual_name: String,
        ?preferred_effective_date: Increase::ACHTransferCreateParams::PreferredEffectiveDate,
        ?require_approval: bool,
        ?routing_number: String,
        ?standard_entry_class_code: Increase::Models::ACHTransferCreateParams::standard_entry_class_code,
        ?transaction_timing: Increase::Models::ACHTransferCreateParams::transaction_timing,
        ?request_options: Increase::request_opts
      ) -> Increase::ACHTransfer

      def retrieve: (
        String ach_transfer_id,
        ?request_options: Increase::request_opts
      ) -> Increase::ACHTransfer

      def list: (
        ?account_id: String,
        ?created_at: Increase::ACHTransferListParams::CreatedAt,
        ?cursor: String,
        ?external_account_id: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?status: Increase::ACHTransferListParams::Status,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::ACHTransfer]

      def approve: (
        String ach_transfer_id,
        ?request_options: Increase::request_opts
      ) -> Increase::ACHTransfer

      def cancel: (
        String ach_transfer_id,
        ?request_options: Increase::request_opts
      ) -> Increase::ACHTransfer

      def initialize: (client: Increase::Client) -> void
    end
  end
end
