module Increase
  module Resources
    class BookkeepingEntries
      def retrieve: (
        String bookkeeping_entry_id,
        ?request_options: Increase::request_opts
      ) -> Increase::BookkeepingEntry

      def list: (
        ?account_id: String,
        ?cursor: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::BookkeepingEntry]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
