module Increase
  module Resources
    class BookkeepingEntrySets
      def create: (
        entries: ::Array[Increase::BookkeepingEntrySetCreateParams::Entry],
        ?date: Time,
        ?transaction_id: String,
        ?request_options: Increase::request_opts
      ) -> Increase::BookkeepingEntrySet

      def retrieve: (
        String bookkeeping_entry_set_id,
        ?request_options: Increase::request_opts
      ) -> Increase::BookkeepingEntrySet

      def list: (
        ?cursor: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?transaction_id: String,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::BookkeepingEntrySet]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
