module Increase
  module Resources
    class BookkeepingAccounts
      def create:
        (
          Increase::Models::BookkeepingAccountCreateParams
          | ::Hash[Symbol, top] params
        ) -> Increase::Models::BookkeepingAccount
        | (
          name: String,
          ?account_id: String,
          ?compliance_category: Increase::Models::BookkeepingAccountCreateParams::compliance_category,
          ?entity_id: String,
          ?request_options: Increase::request_opts
        ) -> Increase::Models::BookkeepingAccount

      def update:
        (
          String bookkeeping_account_id,
          Increase::Models::BookkeepingAccountUpdateParams
          | ::Hash[Symbol, top] params
        ) -> Increase::Models::BookkeepingAccount
        | (
          String bookkeeping_account_id,
          name: String,
          ?request_options: Increase::request_opts
        ) -> Increase::Models::BookkeepingAccount

      def list:
        (
          ?Increase::Models::BookkeepingAccountListParams
          | ::Hash[Symbol, top] params
        ) -> Increase::Page[Increase::Models::BookkeepingAccount]
        | (
          ?cursor: String,
          ?idempotency_key: String,
          ?limit: Integer,
          ?request_options: Increase::request_opts
        ) -> Increase::Page[Increase::Models::BookkeepingAccount]

      def balance:
        (
          String bookkeeping_account_id,
          ?Increase::Models::BookkeepingAccountBalanceParams
          | ::Hash[Symbol, top] params
        ) -> Increase::Models::BookkeepingBalanceLookup
        | (
          String bookkeeping_account_id,
          ?at_time: Time,
          ?request_options: Increase::request_opts
        ) -> Increase::Models::BookkeepingBalanceLookup

      def initialize: (client: Increase::Client) -> void
    end
  end
end
