module Increase
  module Resources
    class CardDisputes
      def create: (
        disputed_transaction_id: String,
        explanation: String,
        ?amount: Integer,
        ?request_options: Increase::request_opts
      ) -> Increase::CardDispute

      def retrieve: (
        String card_dispute_id,
        ?request_options: Increase::request_opts
      ) -> Increase::CardDispute

      def list: (
        ?created_at: Increase::CardDisputeListParams::CreatedAt,
        ?cursor: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?status: Increase::CardDisputeListParams::Status,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::CardDispute]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
