module Increase
  module Resources
    class Cards
      def create: (
        account_id: String,
        ?billing_address: Increase::Models::CardCreateParams::BillingAddress,
        ?description: String,
        ?digital_wallet: Increase::Models::CardCreateParams::DigitalWallet,
        ?entity_id: String,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::Card

      def retrieve: (
        String card_id,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::Card

      def update: (
        String card_id,
        ?billing_address: Increase::Models::CardUpdateParams::BillingAddress,
        ?description: String,
        ?digital_wallet: Increase::Models::CardUpdateParams::DigitalWallet,
        ?entity_id: String,
        ?status: Increase::Models::CardUpdateParams::status,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::Card

      def list: (
        ?account_id: String,
        ?created_at: Increase::Models::CardListParams::CreatedAt,
        ?cursor: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?status: Increase::Models::CardListParams::Status,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::Models::Card]

      def details: (
        String card_id,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::CardDetails

      def initialize: (client: Increase::Client) -> void
    end
  end
end
