module Increase
  module Resources
    class Cards
      def create:
        (
          Increase::Models::CardCreateParams | ::Hash[Symbol, top] params
        ) -> Increase::Models::Card
        | (
          account_id: String,
          billing_address: Increase::Models::CardCreateParams::BillingAddress,
          description: String,
          digital_wallet: Increase::Models::CardCreateParams::DigitalWallet,
          entity_id: String,
          request_options: Increase::request_opts
        ) -> Increase::Models::Card

      def retrieve:
        (
          String card_id,
          ?Increase::Models::CardRetrieveParams | ::Hash[Symbol, top] params
        ) -> Increase::Models::Card
        | (
          String card_id,
          request_options: Increase::request_opts
        ) -> Increase::Models::Card

      def update:
        (
          String card_id,
          ?Increase::Models::CardUpdateParams | ::Hash[Symbol, top] params
        ) -> Increase::Models::Card
        | (
          String card_id,
          billing_address: Increase::Models::CardUpdateParams::BillingAddress,
          description: String,
          digital_wallet: Increase::Models::CardUpdateParams::DigitalWallet,
          entity_id: String,
          status: Increase::Models::CardUpdateParams::status,
          request_options: Increase::request_opts
        ) -> Increase::Models::Card

      def list:
        (
          ?Increase::Models::CardListParams | ::Hash[Symbol, top] params
        ) -> Increase::Page[Increase::Models::Card]
        | (
          account_id: String,
          created_at: Increase::Models::CardListParams::CreatedAt,
          cursor: String,
          idempotency_key: String,
          limit: Integer,
          request_options: Increase::request_opts
        ) -> Increase::Page[Increase::Models::Card]

      def details:
        (
          String card_id,
          ?Increase::Models::CardDetailsParams | ::Hash[Symbol, top] params
        ) -> Increase::Models::CardDetails
        | (
          String card_id,
          request_options: Increase::request_opts
        ) -> Increase::Models::CardDetails

      def initialize: (client: Increase::Client) -> void
    end
  end
end
