module Increase
  module Resources
    class CardPayments
      def retrieve:
        (
          String card_payment_id,
          ?Increase::Models::CardPaymentRetrieveParams
          | ::Hash[Symbol, top] params
        ) -> Increase::Models::CardPayment
        | (
          String card_payment_id,
          request_options: Increase::request_opts
        ) -> Increase::Models::CardPayment

      def list:
        (
          ?Increase::Models::CardPaymentListParams | ::Hash[Symbol, top] params
        ) -> Increase::Page[Increase::Models::CardPayment]
        | (
          account_id: String,
          card_id: String,
          created_at: Increase::Models::CardPaymentListParams::CreatedAt,
          cursor: String,
          limit: Integer,
          request_options: Increase::request_opts
        ) -> Increase::Page[Increase::Models::CardPayment]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
