module Increase
  module Resources
    class CardPayments
      def retrieve: (
        String card_payment_id,
        ?request_options: Increase::request_opts
      ) -> Increase::CardPayment

      def list: (
        ?account_id: String,
        ?card_id: String,
        ?created_at: Increase::CardPaymentListParams::CreatedAt,
        ?cursor: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::CardPayment]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
