module Increase
  module Resources
    class CardPurchaseSupplements
      def retrieve:
        (
          String card_purchase_supplement_id,
          ?Increase::Models::CardPurchaseSupplementRetrieveParams
          | ::Hash[Symbol, top] params
        ) -> Increase::Models::CardPurchaseSupplement
        | (
          String card_purchase_supplement_id,
          request_options: Increase::request_opts
        ) -> Increase::Models::CardPurchaseSupplement

      def list:
        (
          ?Increase::Models::CardPurchaseSupplementListParams
          | ::Hash[Symbol, top] params
        ) -> Increase::Page[Increase::Models::CardPurchaseSupplement]
        | (
          card_payment_id: String,
          created_at: Increase::Models::CardPurchaseSupplementListParams::CreatedAt,
          cursor: String,
          limit: Integer,
          request_options: Increase::request_opts
        ) -> Increase::Page[Increase::Models::CardPurchaseSupplement]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
