module Increase
  module Resources
    class Documents
      def retrieve: (
        String document_id,
        ?request_options: Increase::request_opts
      ) -> Increase::Document

      def list: (
        ?category: Increase::DocumentListParams::Category,
        ?created_at: Increase::DocumentListParams::CreatedAt,
        ?cursor: String,
        ?entity_id: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::Document]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
