module Increase
  module Resources
    class Events
      private def initialize_resources: -> void

      def retrieve: (
        String event_id,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::Event

      def list: (
        ?associated_object_id: String,
        ?category: Increase::Models::EventListParams::Category,
        ?created_at: Increase::Models::EventListParams::CreatedAt,
        ?cursor: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::Models::Event]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
