module Increase
  module Resources
    class EventSubscriptions
      def create: ((Increase::Models::EventSubscriptionCreateParams | ::Hash[Symbol, top]) params) -> Increase::Models::EventSubscription
                | (url: String, oauth_connection_id: String, selected_event_category: Increase::Models::EventSubscriptionCreateParams::selected_event_category, shared_secret: String, request_options: Increase::request_opts) -> Increase::Models::EventSubscription

      def retrieve: (String event_subscription_id, ?(Increase::Models::EventSubscriptionRetrieveParams | ::Hash[Symbol, top]) params) -> Increase::Models::EventSubscription
                  | (String event_subscription_id, request_options: Increase::request_opts) -> Increase::Models::EventSubscription

      def update: (String event_subscription_id, ?(Increase::Models::EventSubscriptionUpdateParams | ::Hash[Symbol, top]) params) -> Increase::Models::EventSubscription
                | (String event_subscription_id, status: Increase::Models::EventSubscriptionUpdateParams::status, request_options: Increase::request_opts) -> Increase::Models::EventSubscription

      def list: (?(Increase::Models::EventSubscriptionListParams | ::Hash[Symbol, top]) params) -> Increase::Page[Increase::Models::EventSubscription]
              | (cursor: String, idempotency_key: String, limit: Integer, request_options: Increase::request_opts) -> Increase::Page[Increase::Models::EventSubscription]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
