module Increase
  module Resources
    class ExternalAccounts
      def create: (
        account_number: String,
        description: String,
        routing_number: String,
        ?account_holder: Increase::Models::ExternalAccountCreateParams::account_holder,
        ?funding: Increase::Models::ExternalAccountCreateParams::funding,
        ?request_options: Increase::request_opts
      ) -> Increase::ExternalAccount

      def retrieve: (
        String external_account_id,
        ?request_options: Increase::request_opts
      ) -> Increase::ExternalAccount

      def update: (
        String external_account_id,
        ?account_holder: Increase::Models::ExternalAccountUpdateParams::account_holder,
        ?description: String,
        ?funding: Increase::Models::ExternalAccountUpdateParams::funding,
        ?status: Increase::Models::ExternalAccountUpdateParams::status,
        ?request_options: Increase::request_opts
      ) -> Increase::ExternalAccount

      def list: (
        ?cursor: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?routing_number: String,
        ?status: Increase::ExternalAccountListParams::Status,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::ExternalAccount]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
