module Increase
  module Resources
    class Files
      def create: (
        file: Increase::Internal::file_input,
        purpose: Increase::Models::FileCreateParams::purpose,
        ?description: String,
        ?request_options: Increase::request_opts
      ) -> Increase::File

      def retrieve: (
        String file_id,
        ?request_options: Increase::request_opts
      ) -> Increase::File

      def list: (
        ?created_at: Increase::FileListParams::CreatedAt,
        ?cursor: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?purpose: Increase::FileListParams::Purpose,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::File]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
