module Increase
  module Resources
    class Groups
      def retrieve: (
        ?request_options: Increase::request_opts
      ) -> Increase::Group

      def initialize: (client: Increase::Client) -> void
    end
  end
end
