module Increase
  module Resources
    class Groups
      private def initialize_resources: -> void

      def retrieve: (
        ?request_options: Increase::request_opts
      ) -> Increase::Models::Group

      def initialize: (client: Increase::Client) -> void
    end
  end
end
