module Increase
  module Resources
    class Groups
      def retrieve:
        (
          ?Increase::Models::GroupRetrieveParams | ::Hash[Symbol, top] params
        ) -> Increase::Models::Group
        | (request_options: Increase::request_opts) -> Increase::Models::Group

      def initialize: (client: Increase::Client) -> void
    end
  end
end
