module Increase
  module Resources
    class InboundWireDrawdownRequests
      def retrieve: (
        String inbound_wire_drawdown_request_id,
        ?request_options: Increase::request_opts
      ) -> Increase::InboundWireDrawdownRequest

      def list: (
        ?cursor: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::InboundWireDrawdownRequest]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
