module Increase
  module Resources
    class InboundMailItems
      def retrieve: (
        String inbound_mail_item_id,
        ?request_options: Increase::request_opts
      ) -> Increase::InboundMailItem

      def list: (
        ?created_at: Increase::InboundMailItemListParams::CreatedAt,
        ?cursor: String,
        ?limit: Integer,
        ?lockbox_id: String,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::InboundMailItem]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
