module Increase
  module Resources
    class InboundRealTimePaymentsTransfers
      def retrieve: (
        String inbound_real_time_payments_transfer_id,
        ?request_options: Increase::request_opts
      ) -> Increase::InboundRealTimePaymentsTransfer

      def list: (
        ?account_id: String,
        ?account_number_id: String,
        ?created_at: Increase::InboundRealTimePaymentsTransferListParams::CreatedAt,
        ?cursor: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::InboundRealTimePaymentsTransfer]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
