module Increase
  module Resources
    class IntrafiExclusions
      def create: (
        bank_name: String,
        entity_id: String,
        ?request_options: Increase::request_opts
      ) -> Increase::IntrafiExclusion

      def retrieve: (
        String intrafi_exclusion_id,
        ?request_options: Increase::request_opts
      ) -> Increase::IntrafiExclusion

      def list: (
        ?cursor: String,
        ?entity_id: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::IntrafiExclusion]

      def archive: (
        String intrafi_exclusion_id,
        ?request_options: Increase::request_opts
      ) -> Increase::IntrafiExclusion

      def initialize: (client: Increase::Client) -> void
    end
  end
end
