module Increase
  module Resources
    class IntrafiBalances
      def intrafi_balance: (
        String account_id,
        ?request_options: Increase::request_opts
      ) -> Increase::IntrafiBalance

      def initialize: (client: Increase::Client) -> void
    end
  end
end
