module Increase
  module Resources
    class IntrafiAccountEnrollments
      private def initialize_resources: -> void

      def create: (
        account_id: String,
        email_address: String,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::IntrafiAccountEnrollment

      def retrieve: (
        String intrafi_account_enrollment_id,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::IntrafiAccountEnrollment

      def list: (
        ?account_id: String,
        ?cursor: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?status: Increase::Models::IntrafiAccountEnrollmentListParams::Status,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::Models::IntrafiAccountEnrollment]

      def unenroll: (
        String intrafi_account_enrollment_id,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::IntrafiAccountEnrollment

      def initialize: (client: Increase::Client) -> void
    end
  end
end
