module Increase
  module Resources
    class IntrafiBalances
      private def initialize_resources: -> void

      def intrafi_balance: (
        String account_id,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::IntrafiBalance

      def initialize: (client: Increase::Client) -> void
    end
  end
end
