module Increase
  module Resources
    class Lockboxes
      def create: (
        account_id: String,
        ?description: String,
        ?recipient_name: String,
        ?request_options: Increase::request_opts
      ) -> Increase::Lockbox

      def retrieve: (
        String lockbox_id,
        ?request_options: Increase::request_opts
      ) -> Increase::Lockbox

      def update: (
        String lockbox_id,
        ?description: String,
        ?recipient_name: String,
        ?status: Increase::Models::LockboxUpdateParams::status,
        ?request_options: Increase::request_opts
      ) -> Increase::Lockbox

      def list: (
        ?account_id: String,
        ?created_at: Increase::LockboxListParams::CreatedAt,
        ?cursor: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::Lockbox]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
