module Increase
  module Resources
    class OAuthConnections
      def retrieve: (
        String oauth_connection_id,
        ?request_options: Increase::request_opts
      ) -> Increase::OAuthConnection

      def list: (
        ?cursor: String,
        ?limit: Integer,
        ?oauth_application_id: String,
        ?status: Increase::OAuthConnectionListParams::Status,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::OAuthConnection]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
