module Increase
  module Resources
    class OAuthTokens
      private def initialize_resources: -> void

      def create: (
        grant_type: Increase::Models::OAuthTokenCreateParams::grant_type,
        ?client_id: String,
        ?client_secret: String,
        ?code: String,
        ?production_token: String,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::OAuthToken

      def initialize: (client: Increase::Client) -> void
    end
  end
end
