module Increase
  module Resources
    class OAuthApplications
      def retrieve: (
        String oauth_application_id,
        ?request_options: Increase::request_opts
      ) -> Increase::OAuthApplication

      def list: (
        ?created_at: Increase::OAuthApplicationListParams::CreatedAt,
        ?cursor: String,
        ?limit: Integer,
        ?status: Increase::OAuthApplicationListParams::Status,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::OAuthApplication]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
