module Increase
  module Resources
    class PendingTransactions
      def create: (
        account_id: String,
        amount: Integer,
        ?description: String,
        ?request_options: Increase::request_opts
      ) -> Increase::PendingTransaction

      def retrieve: (
        String pending_transaction_id,
        ?request_options: Increase::request_opts
      ) -> Increase::PendingTransaction

      def list: (
        ?account_id: String,
        ?category: Increase::PendingTransactionListParams::Category,
        ?created_at: Increase::PendingTransactionListParams::CreatedAt,
        ?cursor: String,
        ?limit: Integer,
        ?route_id: String,
        ?status: Increase::PendingTransactionListParams::Status,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::PendingTransaction]

      def release: (
        String pending_transaction_id,
        ?request_options: Increase::request_opts
      ) -> Increase::PendingTransaction

      def initialize: (client: Increase::Client) -> void
    end
  end
end
