module Increase
  module Resources
    class PhysicalCards
      private def initialize_resources: -> void

      def create: (
        card_id: String,
        cardholder: Increase::Models::PhysicalCardCreateParams::Cardholder,
        shipment: Increase::Models::PhysicalCardCreateParams::Shipment,
        ?physical_card_profile_id: String,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::PhysicalCard

      def retrieve: (
        String physical_card_id,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::PhysicalCard

      def update: (
        String physical_card_id,
        status: Increase::Models::PhysicalCardUpdateParams::status,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::PhysicalCard

      def list: (
        ?card_id: String,
        ?created_at: Increase::Models::PhysicalCardListParams::CreatedAt,
        ?cursor: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::Models::PhysicalCard]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
