module Increase
  module Resources
    class Programs
      def retrieve: (
        String program_id,
        ?request_options: Increase::request_opts
      ) -> Increase::Program

      def list: (
        ?cursor: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::Program]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
