module Increase
  module Resources
    class ProofOfAuthorizationRequestSubmissions
      def create:
        (
          Increase::Models::ProofOfAuthorizationRequestSubmissionCreateParams
          | Hash[Symbol, top] params
        ) -> Increase::Models::ProofOfAuthorizationRequestSubmission
        | (
          authorization_terms: String,
          authorized_at: Time,
          authorizer_email: String,
          authorizer_name: String,
          customer_has_been_offboarded: bool,
          proof_of_authorization_request_id: String,
          validated_account_ownership_via_credential: bool,
          validated_account_ownership_with_account_statement: bool,
          validated_account_ownership_with_microdeposit: bool,
          authorizer_company: String,
          authorizer_ip_address: String,
          request_options: Increase::request_opts
        ) -> Increase::Models::ProofOfAuthorizationRequestSubmission

      def retrieve:
        (
          String proof_of_authorization_request_submission_id,
          ?Increase::Models::ProofOfAuthorizationRequestSubmissionRetrieveParams
          | Hash[Symbol, top] params
        ) -> Increase::Models::ProofOfAuthorizationRequestSubmission
        | (
          String proof_of_authorization_request_submission_id,
          request_options: Increase::request_opts
        ) -> Increase::Models::ProofOfAuthorizationRequestSubmission

      def list:
        (
          ?Increase::Models::ProofOfAuthorizationRequestSubmissionListParams
          | Hash[Symbol, top] params
        ) -> Increase::Page[Increase::Models::ProofOfAuthorizationRequestSubmission]
        | (
          cursor: String,
          idempotency_key: String,
          limit: Integer,
          proof_of_authorization_request_id: String,
          request_options: Increase::request_opts
        ) -> Increase::Page[Increase::Models::ProofOfAuthorizationRequestSubmission]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
