module Increase
  module Resources
    class ProofOfAuthorizationRequests
      def retrieve: (
        String proof_of_authorization_request_id,
        ?request_options: Increase::request_opts
      ) -> Increase::Models::ProofOfAuthorizationRequest

      def list: (
        ?created_at: Increase::Models::ProofOfAuthorizationRequestListParams::CreatedAt,
        ?cursor: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::Models::ProofOfAuthorizationRequest]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
