module Increase
  module Resources
    class RealTimePaymentsTransfers
      def create:
        (
          Increase::Models::RealTimePaymentsTransferCreateParams
          | ::Hash[Symbol, top] params
        ) -> Increase::Models::RealTimePaymentsTransfer
        | (
          amount: Integer,
          creditor_name: String,
          remittance_information: String,
          source_account_number_id: String,
          debtor_name: String,
          destination_account_number: String,
          destination_routing_number: String,
          external_account_id: String,
          require_approval: bool,
          ultimate_creditor_name: String,
          ultimate_debtor_name: String,
          request_options: Increase::request_opts
        ) -> Increase::Models::RealTimePaymentsTransfer

      def retrieve:
        (
          String real_time_payments_transfer_id,
          ?Increase::Models::RealTimePaymentsTransferRetrieveParams
          | ::Hash[Symbol, top] params
        ) -> Increase::Models::RealTimePaymentsTransfer
        | (
          String real_time_payments_transfer_id,
          request_options: Increase::request_opts
        ) -> Increase::Models::RealTimePaymentsTransfer

      def list:
        (
          ?Increase::Models::RealTimePaymentsTransferListParams
          | ::Hash[Symbol, top] params
        ) -> Increase::Page[Increase::Models::RealTimePaymentsTransfer]
        | (
          account_id: String,
          created_at: Increase::Models::RealTimePaymentsTransferListParams::CreatedAt,
          cursor: String,
          external_account_id: String,
          idempotency_key: String,
          limit: Integer,
          request_options: Increase::request_opts
        ) -> Increase::Page[Increase::Models::RealTimePaymentsTransfer]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
