module Increase
  module Resources
    class RealTimeDecisions
      def retrieve: (
        String real_time_decision_id,
        ?request_options: Increase::request_opts
      ) -> Increase::RealTimeDecision

      def action: (
        String real_time_decision_id,
        ?card_authentication: Increase::RealTimeDecisionActionParams::CardAuthentication,
        ?card_authentication_challenge: Increase::RealTimeDecisionActionParams::CardAuthenticationChallenge,
        ?card_authorization: Increase::RealTimeDecisionActionParams::CardAuthorization,
        ?digital_wallet_authentication: Increase::RealTimeDecisionActionParams::DigitalWalletAuthentication,
        ?digital_wallet_token: Increase::RealTimeDecisionActionParams::DigitalWalletToken,
        ?request_options: Increase::request_opts
      ) -> Increase::RealTimeDecision

      def initialize: (client: Increase::Client) -> void
    end
  end
end
