module Increase
  module Resources
    class Simulations
      attr_reader interest_payments: Increase::Resources::Simulations::InterestPayments

      attr_reader fee_payments: Increase::Resources::Simulations::FeePayments

      attr_reader card_authorizations: Increase::Resources::Simulations::CardAuthorizations

      attr_reader card_authorization_expirations: Increase::Resources::Simulations::CardAuthorizationExpirations

      attr_reader card_settlements: Increase::Resources::Simulations::CardSettlements

      attr_reader card_reversals: Increase::Resources::Simulations::CardReversals

      attr_reader card_increments: Increase::Resources::Simulations::CardIncrements

      attr_reader card_fuel_confirmations: Increase::Resources::Simulations::CardFuelConfirmations

      attr_reader card_refunds: Increase::Resources::Simulations::CardRefunds

      attr_reader card_disputes: Increase::Resources::Simulations::CardDisputes

      attr_reader physical_cards: Increase::Resources::Simulations::PhysicalCards

      attr_reader digital_wallet_token_requests: Increase::Resources::Simulations::DigitalWalletTokenRequests

      attr_reader inbound_funds_holds: Increase::Resources::Simulations::InboundFundsHolds

      attr_reader account_transfers: Increase::Resources::Simulations::AccountTransfers

      attr_reader ach_transfers: Increase::Resources::Simulations::ACHTransfers

      attr_reader inbound_ach_transfers: Increase::Resources::Simulations::InboundACHTransfers

      attr_reader wire_transfers: Increase::Resources::Simulations::WireTransfers

      attr_reader inbound_wire_transfers: Increase::Resources::Simulations::InboundWireTransfers

      attr_reader inbound_wire_drawdown_requests: Increase::Resources::Simulations::InboundWireDrawdownRequests

      attr_reader check_transfers: Increase::Resources::Simulations::CheckTransfers

      attr_reader inbound_check_deposits: Increase::Resources::Simulations::InboundCheckDeposits

      attr_reader real_time_payments_transfers: Increase::Resources::Simulations::RealTimePaymentsTransfers

      attr_reader inbound_real_time_payments_transfers: Increase::Resources::Simulations::InboundRealTimePaymentsTransfers

      attr_reader check_deposits: Increase::Resources::Simulations::CheckDeposits

      attr_reader inbound_mail_items: Increase::Resources::Simulations::InboundMailItems

      attr_reader programs: Increase::Resources::Simulations::Programs

      attr_reader account_statements: Increase::Resources::Simulations::AccountStatements

      attr_reader documents: Increase::Resources::Simulations::Documents

      def initialize: (client: Increase::Client) -> void
    end
  end
end
