module Increase
  module Resources
    class Transactions
      def retrieve:
        (
          String transaction_id,
          ?Increase::Models::TransactionRetrieveParams
          | Hash[Symbol, top] params
        ) -> Increase::Models::Transaction
        | (
          String transaction_id,
          request_options: Increase::request_opts
        ) -> Increase::Models::Transaction

      def list:
        (
          ?Increase::Models::TransactionListParams | Hash[Symbol, top] params
        ) -> Increase::Page[Increase::Models::Transaction]
        | (
          account_id: String,
          category: Increase::Models::TransactionListParams::Category,
          created_at: Increase::Models::TransactionListParams::CreatedAt,
          cursor: String,
          limit: Integer,
          route_id: String,
          request_options: Increase::request_opts
        ) -> Increase::Page[Increase::Models::Transaction]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
