module Increase
  module Resources
    class Transactions
      def retrieve: (
        String transaction_id,
        ?request_options: Increase::request_opts
      ) -> Increase::Transaction

      def list: (
        ?account_id: String,
        ?category: Increase::TransactionListParams::Category,
        ?created_at: Increase::TransactionListParams::CreatedAt,
        ?cursor: String,
        ?limit: Integer,
        ?route_id: String,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::Transaction]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
