module Increase
  module Resources
    class WireDrawdownRequests
      def create: (
        account_number_id: String,
        amount: Integer,
        message_to_recipient: String,
        recipient_account_number: String,
        recipient_name: String,
        recipient_routing_number: String,
        ?originator_address_line1: String,
        ?originator_address_line2: String,
        ?originator_address_line3: String,
        ?originator_name: String,
        ?recipient_address_line1: String,
        ?recipient_address_line2: String,
        ?recipient_address_line3: String,
        ?request_options: Increase::request_opts
      ) -> Increase::WireDrawdownRequest

      def retrieve: (
        String wire_drawdown_request_id,
        ?request_options: Increase::request_opts
      ) -> Increase::WireDrawdownRequest

      def list: (
        ?cursor: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?status: Increase::WireDrawdownRequestListParams::Status,
        ?request_options: Increase::request_opts
      ) -> Increase::Internal::Page[Increase::WireDrawdownRequest]

      def initialize: (client: Increase::Client) -> void
    end
  end
end
