# frozen_string_literal: true

module Increase
  module Resources
    class Simulations
      class CardAuthorizations
        # Some parameter documentations has been truncated, see
        # {Increase::Models::Simulations::CardAuthorizationCreateParams} for more details.
        #
        # Simulates a purchase authorization on a [Card](#cards). Depending on the balance
        # available to the card and the `amount` submitted, the authorization activity
        # will result in a [Pending Transaction](#pending-transactions) of type
        # `card_authorization` or a [Declined Transaction](#declined-transactions) of type
        # `card_decline`. You can pass either a Card id or a
        # [Digital Wallet Token](#digital-wallet-tokens) id to simulate the two different
        # ways purchases can be made.
        #
        # @overload create(amount:, authenticated_card_payment_id: nil, card_id: nil, decline_reason: nil, digital_wallet_token_id: nil, direction: nil, event_subscription_id: nil, merchant_acceptor_id: nil, merchant_category_code: nil, merchant_city: nil, merchant_country: nil, merchant_descriptor: nil, merchant_state: nil, network_details: nil, network_risk_score: nil, physical_card_id: nil, terminal_id: nil, request_options: {})
        #
        # @param amount [Integer] The authorization amount in cents.
        #
        # @param authenticated_card_payment_id [String] The identifier of a Card Payment with a `card_authentication` if you want to sim
        #
        # @param card_id [String] The identifier of the Card to be authorized.
        #
        # @param decline_reason [Symbol, Increase::Simulations::CardAuthorizationCreateParams::DeclineReason] Forces a card decline with a specific reason. No real time decision will be sent
        #
        # @param digital_wallet_token_id [String] The identifier of the Digital Wallet Token to be authorized.
        #
        # @param direction [Symbol, Increase::Simulations::CardAuthorizationCreateParams::Direction] The direction describes the direction the funds will move, either from the cardh
        #
        # @param event_subscription_id [String] The identifier of the Event Subscription to use. If provided, will override the
        #
        # @param merchant_acceptor_id [String] The merchant identifier (commonly abbreviated as MID) of the merchant the card i
        #
        # @param merchant_category_code [String] The Merchant Category Code (commonly abbreviated as MCC) of the merchant the car
        #
        # @param merchant_city [String] The city the merchant resides in.
        #
        # @param merchant_country [String] The country the merchant resides in.
        #
        # @param merchant_descriptor [String] The merchant descriptor of the merchant the card is transacting with.
        #
        # @param merchant_state [String] The state the merchant resides in.
        #
        # @param network_details [Increase::Simulations::CardAuthorizationCreateParams::NetworkDetails] Fields specific to a given card network.
        #
        # @param network_risk_score [Integer] The risk score generated by the card network. For Visa this is the Visa Advanced
        #
        # @param physical_card_id [String] The identifier of the Physical Card to be authorized.
        #
        # @param terminal_id [String] The terminal identifier (commonly abbreviated as TID) of the terminal the card i
        #
        # @param request_options [Increase::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [Increase::Models::Simulations::CardAuthorizationCreateResponse]
        #
        # @see Increase::Models::Simulations::CardAuthorizationCreateParams
        def create(params)
          parsed, options = Increase::Simulations::CardAuthorizationCreateParams.dump_request(params)
          @client.request(
            method: :post,
            path: "simulations/card_authorizations",
            body: parsed,
            model: Increase::Models::Simulations::CardAuthorizationCreateResponse,
            options: options
          )
        end

        # @api private
        #
        # @param client [Increase::Client]
        def initialize(client:)
          @client = client
        end
      end
    end
  end
end
