module Increase
  module Resources
    class Simulations
      class AccountStatements
        def create:
          (
            Increase::Models::Simulations::AccountStatementCreateParams
            | Hash[Symbol, top] params
          ) -> Increase::Models::AccountStatement
          | (
            account_id: String,
            request_options: Increase::request_opts
          ) -> Increase::Models::AccountStatement

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
