module Increase
  module Resources
    class Simulations
      class ACHTransfers
        def acknowledge: (
          String ach_transfer_id,
          ?request_options: Increase::request_opts
        ) -> Increase::ACHTransfer

        def create_notification_of_change: (
          String ach_transfer_id,
          change_code: Increase::Models::Simulations::ACHTransferCreateNotificationOfChangeParams::change_code,
          corrected_data: String,
          ?request_options: Increase::request_opts
        ) -> Increase::ACHTransfer

        def return_: (
          String ach_transfer_id,
          ?reason: Increase::Models::Simulations::ACHTransferReturnParams::reason,
          ?request_options: Increase::request_opts
        ) -> Increase::ACHTransfer

        def settle: (
          String ach_transfer_id,
          ?request_options: Increase::request_opts
        ) -> Increase::ACHTransfer

        def submit: (
          String ach_transfer_id,
          ?request_options: Increase::request_opts
        ) -> Increase::ACHTransfer

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
