module Increase
  module Resources
    class Simulations
      class CardDisputes
        private def initialize_resources: -> void

        def action: (
          String card_dispute_id,
          status: Increase::Models::Simulations::CardDisputeActionParams::status,
          ?explanation: String,
          ?request_options: Increase::request_opts
        ) -> Increase::Models::CardDispute

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
