module Increase
  module Resources
    class Simulations
      class CardIncrements
        def create:
          (
            Increase::Models::Simulations::CardIncrementCreateParams
            | ::Hash[Symbol, top] params
          ) -> Increase::Models::CardPayment
          | (
            amount: Integer,
            card_payment_id: String,
            event_subscription_id: String,
            request_options: Increase::request_opts
          ) -> Increase::Models::CardPayment

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
