module Increase
  module Resources
    class Simulations
      class CardRefunds
        private def initialize_resources: -> void

        def create: (
          transaction_id: String,
          ?request_options: Increase::request_opts
        ) -> Increase::Models::Transaction

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
