module Increase
  module Resources
    class Simulations
      class CardSettlements
        def create: (
          card_id: String,
          pending_transaction_id: String,
          ?amount: Integer,
          ?request_options: Increase::request_opts
        ) -> Increase::Transaction

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
