module Increase
  module Resources
    class Simulations
      class CardAuthorizations
        def create: (
          amount: Integer,
          ?authenticated_card_payment_id: String,
          ?card_id: String,
          ?decline_reason: Increase::Models::Simulations::CardAuthorizationCreateParams::decline_reason,
          ?digital_wallet_token_id: String,
          ?direction: Increase::Models::Simulations::CardAuthorizationCreateParams::direction,
          ?event_subscription_id: String,
          ?merchant_acceptor_id: String,
          ?merchant_category_code: String,
          ?merchant_city: String,
          ?merchant_country: String,
          ?merchant_descriptor: String,
          ?merchant_state: String,
          ?network_details: Increase::Simulations::CardAuthorizationCreateParams::NetworkDetails,
          ?network_risk_score: Integer,
          ?physical_card_id: String,
          ?terminal_id: String,
          ?request_options: Increase::request_opts
        ) -> Increase::Models::Simulations::CardAuthorizationCreateResponse

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
