module Increase
  module Resources
    class Simulations
      class CheckDeposits
        private def initialize_resources: -> void

        def reject: (
          String check_deposit_id,
          ?request_options: Increase::request_opts
        ) -> Increase::Models::CheckDeposit

        def return_: (
          String check_deposit_id,
          ?request_options: Increase::request_opts
        ) -> Increase::Models::CheckDeposit

        def submit: (
          String check_deposit_id,
          ?request_options: Increase::request_opts
        ) -> Increase::Models::CheckDeposit

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
