module Increase
  module Resources
    class Simulations
      class CheckTransfers
        def mail: (
          String check_transfer_id,
          ?request_options: Increase::request_opts
        ) -> Increase::CheckTransfer

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
