module Increase
  module Resources
    class Simulations
      class CheckTransfers
        def mail:
          (
            String check_transfer_id,
            ?Increase::Models::Simulations::CheckTransferMailParams
            | Hash[Symbol, top] params
          ) -> Increase::Models::CheckTransfer
          | (
            String check_transfer_id,
            request_options: Increase::request_opts
          ) -> Increase::Models::CheckTransfer

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
