module Increase
  module Resources
    class Simulations
      class InboundFundsHolds
        def release:
          (
            String inbound_funds_hold_id,
            ?Increase::Models::Simulations::InboundFundsHoldReleaseParams
            | ::Hash[Symbol, top] params
          ) -> Increase::Models::Simulations::InboundFundsHoldReleaseResponse
          | (
            String inbound_funds_hold_id,
            request_options: Increase::request_opts
          ) -> Increase::Models::Simulations::InboundFundsHoldReleaseResponse

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
