module Increase
  module Resources
    class Simulations
      class InboundACHTransfers
        def create: (
          account_number_id: String,
          amount: Integer,
          ?addenda: Increase::Simulations::InboundACHTransferCreateParams::Addenda,
          ?company_descriptive_date: String,
          ?company_discretionary_data: String,
          ?company_entry_description: String,
          ?company_id: String,
          ?company_name: String,
          ?receiver_id_number: String,
          ?receiver_name: String,
          ?resolve_at: Time,
          ?standard_entry_class_code: Increase::Models::Simulations::InboundACHTransferCreateParams::standard_entry_class_code,
          ?request_options: Increase::request_opts
        ) -> Increase::InboundACHTransfer

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
