module Increase
  module Resources
    class Simulations
      class InboundRealTimePaymentsTransfers
        def create: (
          account_number_id: String,
          amount: Integer,
          ?debtor_account_number: String,
          ?debtor_name: String,
          ?debtor_routing_number: String,
          ?remittance_information: String,
          ?request_for_payment_id: String,
          ?request_options: Increase::request_opts
        ) -> Increase::InboundRealTimePaymentsTransfer

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
