module Increase
  module Resources
    class Simulations
      class InboundCheckDeposits
        def create: (
          account_number_id: String,
          amount: Integer,
          check_number: String,
          ?request_options: Increase::request_opts
        ) -> Increase::InboundCheckDeposit

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
