module Increase
  module Resources
    class Simulations
      class InboundMailItems
        def create: (
          amount: Integer,
          lockbox_id: String,
          ?contents_file_id: String,
          ?request_options: Increase::request_opts
        ) -> Increase::InboundMailItem

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
