module Increase
  module Resources
    class Simulations
      class InboundWireTransfers
        def create: (
          account_number_id: String,
          amount: Integer,
          ?beneficiary_address_line1: String,
          ?beneficiary_address_line2: String,
          ?beneficiary_address_line3: String,
          ?beneficiary_name: String,
          ?beneficiary_reference: String,
          ?originator_address_line1: String,
          ?originator_address_line2: String,
          ?originator_address_line3: String,
          ?originator_name: String,
          ?originator_routing_number: String,
          ?originator_to_beneficiary_information_line1: String,
          ?originator_to_beneficiary_information_line2: String,
          ?originator_to_beneficiary_information_line3: String,
          ?originator_to_beneficiary_information_line4: String,
          ?sender_reference: String,
          ?wire_drawdown_request_id: String,
          ?request_options: Increase::request_opts
        ) -> Increase::InboundWireTransfer

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
