module Increase
  module Resources
    class Simulations
      class InboundWireDrawdownRequests
        def create: (
          amount: Integer,
          beneficiary_account_number: String,
          beneficiary_routing_number: String,
          currency: String,
          message_to_recipient: String,
          originator_account_number: String,
          originator_routing_number: String,
          recipient_account_number_id: String,
          ?beneficiary_address_line1: String,
          ?beneficiary_address_line2: String,
          ?beneficiary_address_line3: String,
          ?beneficiary_name: String,
          ?originator_address_line1: String,
          ?originator_address_line2: String,
          ?originator_address_line3: String,
          ?originator_name: String,
          ?originator_to_beneficiary_information_line1: String,
          ?originator_to_beneficiary_information_line2: String,
          ?originator_to_beneficiary_information_line3: String,
          ?originator_to_beneficiary_information_line4: String,
          ?request_options: Increase::request_opts
        ) -> Increase::InboundWireDrawdownRequest

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
