module Increase
  module Resources
    class Simulations
      class InterestPayments
        def create:
          (
            Increase::Models::Simulations::InterestPaymentCreateParams
            | Hash[Symbol, top] params
          ) -> Increase::Models::Transaction
          | (
            account_id: String,
            amount: Integer,
            period_end: Time,
            period_start: Time,
            request_options: Increase::request_opts
          ) -> Increase::Models::Transaction

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
