module Increase
  module Resources
    class Simulations
      class PhysicalCards
        def advance_shipment: (
          String physical_card_id,
          shipment_status: Increase::Models::Simulations::PhysicalCardAdvanceShipmentParams::shipment_status,
          ?request_options: Increase::request_opts
        ) -> Increase::PhysicalCard

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
