module Increase
  module Resources
    class Simulations
      class Programs
        def create: (
          name: String,
          ?request_options: Increase::request_opts
        ) -> Increase::Program

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
