module Increase
  module Resources
    class Simulations
      class RealTimePaymentsTransfers
        def complete: (
          String real_time_payments_transfer_id,
          ?rejection: Increase::Simulations::RealTimePaymentsTransferCompleteParams::Rejection,
          ?request_options: Increase::request_opts
        ) -> Increase::RealTimePaymentsTransfer

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
