module Increase
  module Resources
    class Simulations
      class WireTransfers
        private def initialize_resources: -> void

        def reverse: (
          String wire_transfer_id,
          ?request_options: Increase::request_opts
        ) -> Increase::Models::WireTransfer

        def submit: (
          String wire_transfer_id,
          ?request_options: Increase::request_opts
        ) -> Increase::Models::WireTransfer

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
