module Increase
  module Resources
    class Simulations
      class WireTransfers
        def reverse:
          (
            String wire_transfer_id,
            ?Increase::Models::Simulations::WireTransferReverseParams
            | ::Hash[Symbol, top] params
          ) -> Increase::Models::WireTransfer
          | (
            String wire_transfer_id,
            request_options: Increase::request_opts
          ) -> Increase::Models::WireTransfer

        def submit:
          (
            String wire_transfer_id,
            ?Increase::Models::Simulations::WireTransferSubmitParams
            | ::Hash[Symbol, top] params
          ) -> Increase::Models::WireTransfer
          | (
            String wire_transfer_id,
            request_options: Increase::request_opts
          ) -> Increase::Models::WireTransfer

        def initialize: (client: Increase::Client) -> void
      end
    end
  end
end
