module Increase
  module Internal
    class Page[Elem]
      include Increase::Internal::Type::BasePage[Elem]

      attr_accessor data: ::Array[Elem]?

      attr_accessor next_cursor: String?

      def inspect: -> String
    end
  end
end
