module Increase
  module Type
    class ArrayOf
      include Increase::Type::Converter

      def self.[]: (
        ::Hash[Symbol, top]
        | ^-> Increase::Type::Converter::input
        | Increase::Type::Converter::input type_info,
        ?::Hash[Symbol, top] spec
      ) -> instance

      def ===: (top other) -> bool

      def ==: (top other) -> bool

      def coerce: (
        Enumerable[top] | top value,
        state: Increase::Type::Converter::state
      ) -> (::Array[top] | top)

      def dump: (Enumerable[top] | top value) -> (::Array[top] | top)

      def item_type: -> top

      def nilable?: -> bool

      def initialize: (
        ::Hash[Symbol, top]
        | ^-> Increase::Type::Converter::input
        | Increase::Type::Converter::input type_info,
        ?::Hash[Symbol, top] spec
      ) -> void
    end
  end
end
