module Increase
  module Type
    class Unknown
      extend Increase::Type::Converter

      def self.===: (top other) -> bool

      def self.==: (top other) -> bool

      def self.coerce: (
        top value,
        state: Increase::Type::Converter::state
      ) -> top

      def self.dump: (top value) -> top
    end
  end
end
