# frozen_string_literal: true

module Increase
  module Models
    module Simulations
      # @see Increase::Resources::Simulations::CardAuthorizations#create
      class CardAuthorizationCreateParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        # @!attribute amount
        #   The authorization amount in cents.
        #
        #   @return [Integer]
        required :amount, Integer

        # @!attribute authenticated_card_payment_id
        #   The identifier of a Card Payment with a `card_authentication` if you want to
        #   simulate an authenticated authorization.
        #
        #   @return [String, nil]
        optional :authenticated_card_payment_id, String

        # @!attribute card_id
        #   The identifier of the Card to be authorized.
        #
        #   @return [String, nil]
        optional :card_id, String

        # @!attribute decline_reason
        #   Forces a card decline with a specific reason. No real time decision will be
        #   sent.
        #
        #   @return [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::DeclineReason, nil]
        optional :decline_reason, enum: -> { Increase::Simulations::CardAuthorizationCreateParams::DeclineReason }

        # @!attribute digital_wallet_token_id
        #   The identifier of the Digital Wallet Token to be authorized.
        #
        #   @return [String, nil]
        optional :digital_wallet_token_id, String

        # @!attribute event_subscription_id
        #   The identifier of the Event Subscription to use. If provided, will override the
        #   default real time event subscription. Because you can only create one real time
        #   decision event subscription, you can use this field to route events to any
        #   specified event subscription for testing purposes.
        #
        #   @return [String, nil]
        optional :event_subscription_id, String

        # @!attribute merchant_acceptor_id
        #   The merchant identifier (commonly abbreviated as MID) of the merchant the card
        #   is transacting with.
        #
        #   @return [String, nil]
        optional :merchant_acceptor_id, String

        # @!attribute merchant_category_code
        #   The Merchant Category Code (commonly abbreviated as MCC) of the merchant the
        #   card is transacting with.
        #
        #   @return [String, nil]
        optional :merchant_category_code, String

        # @!attribute merchant_city
        #   The city the merchant resides in.
        #
        #   @return [String, nil]
        optional :merchant_city, String

        # @!attribute merchant_country
        #   The country the merchant resides in.
        #
        #   @return [String, nil]
        optional :merchant_country, String

        # @!attribute merchant_descriptor
        #   The merchant descriptor of the merchant the card is transacting with.
        #
        #   @return [String, nil]
        optional :merchant_descriptor, String

        # @!attribute merchant_state
        #   The state the merchant resides in.
        #
        #   @return [String, nil]
        optional :merchant_state, String

        # @!attribute network_details
        #   Fields specific to a given card network.
        #
        #   @return [Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails, nil]
        optional :network_details, -> { Increase::Simulations::CardAuthorizationCreateParams::NetworkDetails }

        # @!attribute network_risk_score
        #   The risk score generated by the card network. For Visa this is the Visa Advanced
        #   Authorization risk score, from 0 to 99, where 99 is the riskiest.
        #
        #   @return [Integer, nil]
        optional :network_risk_score, Integer

        # @!attribute physical_card_id
        #   The identifier of the Physical Card to be authorized.
        #
        #   @return [String, nil]
        optional :physical_card_id, String

        # @!attribute processing_category
        #   Fields specific to a specific type of authorization, such as Automatic Fuel
        #   Dispensers, Refund Authorizations, or Cash Disbursements.
        #
        #   @return [Increase::Models::Simulations::CardAuthorizationCreateParams::ProcessingCategory, nil]
        optional :processing_category,
                 -> { Increase::Simulations::CardAuthorizationCreateParams::ProcessingCategory }

        # @!attribute terminal_id
        #   The terminal identifier (commonly abbreviated as TID) of the terminal the card
        #   is transacting with.
        #
        #   @return [String, nil]
        optional :terminal_id, String

        # @!method initialize(amount:, authenticated_card_payment_id: nil, card_id: nil, decline_reason: nil, digital_wallet_token_id: nil, event_subscription_id: nil, merchant_acceptor_id: nil, merchant_category_code: nil, merchant_city: nil, merchant_country: nil, merchant_descriptor: nil, merchant_state: nil, network_details: nil, network_risk_score: nil, physical_card_id: nil, processing_category: nil, terminal_id: nil, request_options: {})
        #   Some parameter documentations has been truncated, see
        #   {Increase::Models::Simulations::CardAuthorizationCreateParams} for more details.
        #
        #   @param amount [Integer] The authorization amount in cents.
        #
        #   @param authenticated_card_payment_id [String] The identifier of a Card Payment with a `card_authentication` if you want to sim
        #
        #   @param card_id [String] The identifier of the Card to be authorized.
        #
        #   @param decline_reason [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::DeclineReason] Forces a card decline with a specific reason. No real time decision will be sent
        #
        #   @param digital_wallet_token_id [String] The identifier of the Digital Wallet Token to be authorized.
        #
        #   @param event_subscription_id [String] The identifier of the Event Subscription to use. If provided, will override the
        #
        #   @param merchant_acceptor_id [String] The merchant identifier (commonly abbreviated as MID) of the merchant the card i
        #
        #   @param merchant_category_code [String] The Merchant Category Code (commonly abbreviated as MCC) of the merchant the car
        #
        #   @param merchant_city [String] The city the merchant resides in.
        #
        #   @param merchant_country [String] The country the merchant resides in.
        #
        #   @param merchant_descriptor [String] The merchant descriptor of the merchant the card is transacting with.
        #
        #   @param merchant_state [String] The state the merchant resides in.
        #
        #   @param network_details [Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails] Fields specific to a given card network.
        #
        #   @param network_risk_score [Integer] The risk score generated by the card network. For Visa this is the Visa Advanced
        #
        #   @param physical_card_id [String] The identifier of the Physical Card to be authorized.
        #
        #   @param processing_category [Increase::Models::Simulations::CardAuthorizationCreateParams::ProcessingCategory] Fields specific to a specific type of authorization, such as Automatic Fuel Disp
        #
        #   @param terminal_id [String] The terminal identifier (commonly abbreviated as TID) of the terminal the card i
        #
        #   @param request_options [Increase::RequestOptions, Hash{Symbol=>Object}]

        # Forces a card decline with a specific reason. No real time decision will be
        # sent.
        module DeclineReason
          extend Increase::Internal::Type::Enum

          # The account has been closed.
          ACCOUNT_CLOSED = :account_closed

          # The Card was not active.
          CARD_NOT_ACTIVE = :card_not_active

          # The Card has been canceled.
          CARD_CANCELED = :card_canceled

          # The Physical Card was not active.
          PHYSICAL_CARD_NOT_ACTIVE = :physical_card_not_active

          # The account's entity was not active.
          ENTITY_NOT_ACTIVE = :entity_not_active

          # The account was inactive.
          GROUP_LOCKED = :group_locked

          # The Card's Account did not have a sufficient available balance.
          INSUFFICIENT_FUNDS = :insufficient_funds

          # The given CVV2 did not match the card's value.
          CVV2_MISMATCH = :cvv2_mismatch

          # The given PIN did not match the card's value.
          PIN_MISMATCH = :pin_mismatch

          # The given expiration date did not match the card's value. Only applies when a CVV2 is present.
          CARD_EXPIRATION_MISMATCH = :card_expiration_mismatch

          # The attempted card transaction is not allowed per Increase's terms.
          TRANSACTION_NOT_ALLOWED = :transaction_not_allowed

          # The transaction was blocked by a Limit.
          BREACHES_LIMIT = :breaches_limit

          # Your application declined the transaction via webhook.
          WEBHOOK_DECLINED = :webhook_declined

          # Your application webhook did not respond without the required timeout.
          WEBHOOK_TIMED_OUT = :webhook_timed_out

          # Declined by stand-in processing.
          DECLINED_BY_STAND_IN_PROCESSING = :declined_by_stand_in_processing

          # The card read had an invalid CVV, dCVV, or authorization request cryptogram.
          INVALID_PHYSICAL_CARD = :invalid_physical_card

          # The original card authorization for this incremental authorization does not exist.
          MISSING_ORIGINAL_AUTHORIZATION = :missing_original_authorization

          # The transaction was declined because the 3DS authentication failed.
          FAILED_3DS_AUTHENTICATION = :failed_3ds_authentication

          # The transaction was suspected to be used by a card tester to test for valid card numbers.
          SUSPECTED_CARD_TESTING = :suspected_card_testing

          # The transaction was suspected to be fraudulent. Please reach out to support@increase.com for more information.
          SUSPECTED_FRAUD = :suspected_fraud

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        class NetworkDetails < Increase::Internal::Type::BaseModel
          # @!attribute visa
          #   Fields specific to the Visa network.
          #
          #   @return [Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa]
          required :visa, -> { Increase::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa }

          # @!method initialize(visa:)
          #   Fields specific to a given card network.
          #
          #   @param visa [Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa] Fields specific to the Visa network.

          # @see Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails#visa
          class Visa < Increase::Internal::Type::BaseModel
            # @!attribute stand_in_processing_reason
            #   The reason code for the stand-in processing.
            #
            #   @return [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa::StandInProcessingReason, nil]
            optional :stand_in_processing_reason,
                     enum: -> { Increase::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa::StandInProcessingReason }

            # @!method initialize(stand_in_processing_reason: nil)
            #   Fields specific to the Visa network.
            #
            #   @param stand_in_processing_reason [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa::StandInProcessingReason] The reason code for the stand-in processing.

            # The reason code for the stand-in processing.
            #
            # @see Increase::Models::Simulations::CardAuthorizationCreateParams::NetworkDetails::Visa#stand_in_processing_reason
            module StandInProcessingReason
              extend Increase::Internal::Type::Enum

              # Increase failed to process the authorization in a timely manner.
              ISSUER_ERROR = :issuer_error

              # The physical card read had an invalid CVV, dCVV, or authorization request cryptogram.
              INVALID_PHYSICAL_CARD = :invalid_physical_card

              # The 3DS cardholder authentication verification value was invalid.
              INVALID_CARDHOLDER_AUTHENTICATION_VERIFICATION_VALUE =
                :invalid_cardholder_authentication_verification_value

              # An internal Visa error occurred. Visa uses this reason code for certain expected occurrences as well, such as Application Transaction Counter (ATC) replays.
              INTERNAL_VISA_ERROR = :internal_visa_error

              # The merchant has enabled Visa's Transaction Advisory Service and requires further authentication to perform the transaction. In practice this is often utilized at fuel pumps to tell the cardholder to see the cashier.
              MERCHANT_TRANSACTION_ADVISORY_SERVICE_AUTHENTICATION_REQUIRED =
                :merchant_transaction_advisory_service_authentication_required

              # The transaction was blocked by Visa's Payment Fraud Disruption service due to fraudulent Acquirer behavior, such as card testing.
              PAYMENT_FRAUD_DISRUPTION_ACQUIRER_BLOCK = :payment_fraud_disruption_acquirer_block

              # An unspecific reason for stand-in processing.
              OTHER = :other

              # @!method self.values
              #   @return [Array<Symbol>]
            end
          end
        end

        class ProcessingCategory < Increase::Internal::Type::BaseModel
          # @!attribute category
          #   The processing category describes the intent behind the authorization, such as
          #   whether it was used for bill payments or an automatic fuel dispenser.
          #
          #   @return [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::ProcessingCategory::Category]
          required :category,
                   enum: -> { Increase::Simulations::CardAuthorizationCreateParams::ProcessingCategory::Category }

          # @!method initialize(category:)
          #   Some parameter documentations has been truncated, see
          #   {Increase::Models::Simulations::CardAuthorizationCreateParams::ProcessingCategory}
          #   for more details.
          #
          #   Fields specific to a specific type of authorization, such as Automatic Fuel
          #   Dispensers, Refund Authorizations, or Cash Disbursements.
          #
          #   @param category [Symbol, Increase::Models::Simulations::CardAuthorizationCreateParams::ProcessingCategory::Category] The processing category describes the intent behind the authorization, such as w

          # The processing category describes the intent behind the authorization, such as
          # whether it was used for bill payments or an automatic fuel dispenser.
          #
          # @see Increase::Models::Simulations::CardAuthorizationCreateParams::ProcessingCategory#category
          module Category
            extend Increase::Internal::Type::Enum

            # Account funding transactions are transactions used to e.g., fund an account or transfer funds between accounts.
            ACCOUNT_FUNDING = :account_funding

            # Automatic fuel dispenser authorizations occur when a card is used at a gas pump, prior to the actual transaction amount being known. They are followed by an advice message that updates the amount of the pending transaction.
            AUTOMATIC_FUEL_DISPENSER = :automatic_fuel_dispenser

            # A transaction used to pay a bill.
            BILL_PAYMENT = :bill_payment

            # Original credit transactions are used to send money to a cardholder.
            ORIGINAL_CREDIT = :original_credit

            # A regular purchase.
            PURCHASE = :purchase

            # Quasi-cash transactions represent purchases of items which may be convertible to cash.
            QUASI_CASH = :quasi_cash

            # A refund card authorization, sometimes referred to as a credit voucher authorization, where funds are credited to the cardholder.
            REFUND = :refund

            # Cash disbursement transactions are used to withdraw cash from an ATM or a point of sale.
            CASH_DISBURSEMENT = :cash_disbursement

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end
      end
    end
  end
end
