module Increase
  module Models
    type account_update_params =
      { name: String } & Increase::Internal::Type::request_parameters

    class AccountUpdateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_reader name: String?

      def name=: (String) -> String

      def initialize: (
        ?name: String,
        ?request_options: Increase::request_opts
      ) -> void
    end
  end
end
