module Increase
  module Models
    type account_list_params =
      {
        created_at: Increase::AccountListParams::CreatedAt,
        cursor: String,
        entity_id: String,
        idempotency_key: String,
        informational_entity_id: String,
        limit: Integer,
        program_id: String,
        status: Increase::AccountListParams::Status
      }
      & Increase::Internal::Type::request_parameters

    class AccountListParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_reader created_at: Increase::AccountListParams::CreatedAt?

      def created_at=: (
        Increase::AccountListParams::CreatedAt
      ) -> Increase::AccountListParams::CreatedAt

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader entity_id: String?

      def entity_id=: (String) -> String

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      attr_reader informational_entity_id: String?

      def informational_entity_id=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader program_id: String?

      def program_id=: (String) -> String

      attr_reader status: Increase::AccountListParams::Status?

      def status=: (
        Increase::AccountListParams::Status
      ) -> Increase::AccountListParams::Status

      def initialize: (
        ?created_at: Increase::AccountListParams::CreatedAt,
        ?cursor: String,
        ?entity_id: String,
        ?idempotency_key: String,
        ?informational_entity_id: String,
        ?limit: Integer,
        ?program_id: String,
        ?status: Increase::AccountListParams::Status,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        created_at: Increase::AccountListParams::CreatedAt,
        cursor: String,
        entity_id: String,
        idempotency_key: String,
        informational_entity_id: String,
        limit: Integer,
        program_id: String,
        status: Increase::AccountListParams::Status,
        request_options: Increase::RequestOptions
      }

      type created_at =
        { after: Time, before: Time, on_or_after: Time, on_or_before: Time }

      class CreatedAt < Increase::Internal::Type::BaseModel
        attr_reader after: Time?

        def after=: (Time) -> Time

        attr_reader before: Time?

        def before=: (Time) -> Time

        attr_reader on_or_after: Time?

        def on_or_after=: (Time) -> Time

        attr_reader on_or_before: Time?

        def on_or_before=: (Time) -> Time

        def initialize: (
          ?after: Time,
          ?before: Time,
          ?on_or_after: Time,
          ?on_or_before: Time
        ) -> void

        def to_hash: -> {
          after: Time,
          before: Time,
          on_or_after: Time,
          on_or_before: Time
        }
      end

      type status =
        { in_: ::Array[Increase::Models::AccountListParams::Status::in_] }

      class Status < Increase::Internal::Type::BaseModel
        attr_reader in_: ::Array[Increase::Models::AccountListParams::Status::in_]?

        def in_=: (
          ::Array[Increase::Models::AccountListParams::Status::in_]
        ) -> ::Array[Increase::Models::AccountListParams::Status::in_]

        def initialize: (
          ?in_: ::Array[Increase::Models::AccountListParams::Status::in_]
        ) -> void

        def to_hash: -> {
          in_: ::Array[Increase::Models::AccountListParams::Status::in_]
        }

        type in_ = :closed | :open

        module In
          extend Increase::Internal::Type::Enum

          # Closed Accounts on which no new activity can occur.
          CLOSED: :closed

          # Open Accounts that are ready to use.
          OPEN: :open

          def self?.values: -> ::Array[Increase::Models::AccountListParams::Status::in_]
        end
      end
    end
  end
end
