module Increase
  module Models
    type account_create_params =
      {
        name: String,
        entity_id: String,
        informational_entity_id: String,
        program_id: String
      }
      & Increase::Internal::Type::request_parameters

    class AccountCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor name: String

      attr_reader entity_id: String?

      def entity_id=: (String) -> String

      attr_reader informational_entity_id: String?

      def informational_entity_id=: (String) -> String

      attr_reader program_id: String?

      def program_id=: (String) -> String

      def initialize: (
        name: String,
        ?entity_id: String,
        ?informational_entity_id: String,
        ?program_id: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> Increase::Models::account_create_params
    end
  end
end
