module Increase
  module Models
    type ach_transfer_cancel_params =
      {  } & Increase::Internal::Type::request_parameters

    class ACHTransferCancelParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      def initialize: (?request_options: Increase::request_opts) -> void

      def to_hash: -> Increase::Models::ach_transfer_cancel_params
    end
  end
end
