module Increase
  module Models
    type balance_lookup =
      {
        account_id: String,
        available_balance: Integer,
        current_balance: Integer,
        type: Increase::Models::BalanceLookup::type_
      }

    class BalanceLookup < Increase::Internal::Type::BaseModel
      attr_accessor account_id: String

      attr_accessor available_balance: Integer

      attr_accessor current_balance: Integer

      attr_accessor type: Increase::Models::BalanceLookup::type_

      def initialize: (
        account_id: String,
        available_balance: Integer,
        current_balance: Integer,
        type: Increase::Models::BalanceLookup::type_
      ) -> void

      def to_hash: -> Increase::Models::balance_lookup

      type type_ = :balance_lookup

      module Type
        extend Increase::Internal::Type::Enum

        BALANCE_LOOKUP: :balance_lookup

        def self?.values: -> ::Array[Increase::Models::BalanceLookup::type_]
      end
    end
  end
end
