module Increase
  module Models
    type bookkeeping_entry_set_retrieve_params =
      {  } & Increase::Internal::Type::request_parameters

    class BookkeepingEntrySetRetrieveParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      def initialize: (?request_options: Increase::request_opts) -> void

      def to_hash: -> { request_options: Increase::RequestOptions }
    end
  end
end
