module Increase
  module Models
    type bookkeeping_entry_list_params =
      { account_id: String, cursor: String, limit: Integer }
      & Increase::Internal::Type::request_parameters

    class BookkeepingEntryListParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      def initialize: (
        ?account_id: String,
        ?cursor: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> Increase::Models::bookkeeping_entry_list_params
    end
  end
end
