module Increase
  module Models
    type bookkeeping_balance_lookup =
      {
        balance: Integer,
        bookkeeping_account_id: String,
        type: Increase::BookkeepingBalanceLookup::type_
      }

    class BookkeepingBalanceLookup < Increase::Internal::Type::BaseModel
      attr_accessor balance: Integer

      attr_accessor bookkeeping_account_id: String

      attr_accessor type: Increase::BookkeepingBalanceLookup::type_

      def initialize: (
        balance: Integer,
        bookkeeping_account_id: String,
        type: Increase::BookkeepingBalanceLookup::type_
      ) -> void

      type type_ = :bookkeeping_balance_lookup

      module Type
        extend Increase::Internal::Type::Enum

        BOOKKEEPING_BALANCE_LOOKUP: :bookkeeping_balance_lookup

        def self?.values: -> ::Array[Increase::BookkeepingBalanceLookup::type_]
      end
    end
  end
end
