module Increase
  module Models
    type bookkeeping_entry_set_list_params =
      {
        cursor: String,
        idempotency_key: String,
        limit: Integer,
        transaction_id: String
      }
      & Increase::request_parameters

    class BookkeepingEntrySetListParams < Increase::BaseModel
      extend Increase::RequestParameters::Converter
      include Increase::RequestParameters

      attr_reader cursor: String?

      def cursor=: (String) -> void

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> void

      attr_reader limit: Integer?

      def limit=: (Integer) -> void

      attr_reader transaction_id: String?

      def transaction_id=: (String) -> void

      def initialize:
        (
          cursor: String,
          idempotency_key: String,
          limit: Integer,
          transaction_id: String,
          request_options: Increase::request_opts
        ) -> void
        | (
          ?Increase::Models::bookkeeping_entry_set_list_params
          | Increase::BaseModel data
        ) -> void

      def to_hash: -> Increase::Models::bookkeeping_entry_set_list_params
    end
  end
end
