module Increase
  module Models
    type bookkeeping_entry_set =
      {
        id: String,
        created_at: Time,
        date: Time,
        entries: ::Array[Increase::BookkeepingEntrySet::Entry],
        idempotency_key: String?,
        transaction_id: String?,
        type: Increase::BookkeepingEntrySet::type_
      }

    class BookkeepingEntrySet < Increase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor date: Time

      attr_accessor entries: ::Array[Increase::BookkeepingEntrySet::Entry]

      attr_accessor idempotency_key: String?

      attr_accessor transaction_id: String?

      attr_accessor type: Increase::BookkeepingEntrySet::type_

      def initialize: (
        id: String,
        created_at: Time,
        date: Time,
        entries: ::Array[Increase::BookkeepingEntrySet::Entry],
        idempotency_key: String?,
        transaction_id: String?,
        type: Increase::BookkeepingEntrySet::type_
      ) -> void

      type entry = { id: String, account_id: String, amount: Integer }

      class Entry < Increase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor account_id: String

        attr_accessor amount: Integer

        def initialize: (
          id: String,
          account_id: String,
          amount: Integer
        ) -> void
      end

      type type_ = :bookkeeping_entry_set

      module Type
        extend Increase::Internal::Type::Enum

        BOOKKEEPING_ENTRY_SET: :bookkeeping_entry_set

        def self?.values: -> ::Array[Increase::BookkeepingEntrySet::type_]
      end
    end
  end
end
