module Increase
  module Models
    type card_dispute_retrieve_params = {  } & Increase::request_parameters

    class CardDisputeRetrieveParams < Increase::BaseModel
      extend Increase::RequestParameters::Converter
      include Increase::RequestParameters

      def initialize: (?request_options: Increase::request_opts) -> void

      def to_hash: -> Increase::Models::card_dispute_retrieve_params
    end
  end
end
