module Increase
  module Models
    type card_dispute_create_params =
      { disputed_transaction_id: String, explanation: String, amount: Integer }
      & Increase::Internal::Type::request_parameters

    class CardDisputeCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor disputed_transaction_id: String

      attr_accessor explanation: String

      attr_reader amount: Integer?

      def amount=: (Integer) -> Integer

      def initialize: (
        disputed_transaction_id: String,
        explanation: String,
        ?amount: Integer,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> Increase::Models::card_dispute_create_params
    end
  end
end
