module Increase
  module Models
    type card_purchase_supplement_list_params =
      {
        card_payment_id: String,
        created_at: Increase::Models::CardPurchaseSupplementListParams::CreatedAt,
        cursor: String,
        limit: Integer
      }
      & Increase::request_parameters

    class CardPurchaseSupplementListParams < Increase::BaseModel
      extend Increase::RequestParameters::Converter
      include Increase::RequestParameters

      attr_reader card_payment_id: String?

      def card_payment_id=: (String) -> String

      attr_reader created_at: Increase::Models::CardPurchaseSupplementListParams::CreatedAt?

      def created_at=: (
        Increase::Models::CardPurchaseSupplementListParams::CreatedAt
      ) -> Increase::Models::CardPurchaseSupplementListParams::CreatedAt

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      def initialize:
        (
          ?card_payment_id: String,
          ?created_at: Increase::Models::CardPurchaseSupplementListParams::CreatedAt,
          ?cursor: String,
          ?limit: Integer,
          ?request_options: Increase::request_opts
        ) -> void
        | (
          ?Increase::Models::card_purchase_supplement_list_params
          | Increase::BaseModel data
        ) -> void

      def to_hash: -> Increase::Models::card_purchase_supplement_list_params

      type created_at =
        { after: Time, before: Time, on_or_after: Time, on_or_before: Time }

      class CreatedAt < Increase::BaseModel
        attr_reader after: Time?

        def after=: (Time) -> Time

        attr_reader before: Time?

        def before=: (Time) -> Time

        attr_reader on_or_after: Time?

        def on_or_after=: (Time) -> Time

        attr_reader on_or_before: Time?

        def on_or_before=: (Time) -> Time

        def initialize:
          (
            ?after: Time,
            ?before: Time,
            ?on_or_after: Time,
            ?on_or_before: Time
          ) -> void
          | (
            ?Increase::Models::CardPurchaseSupplementListParams::created_at
            | Increase::BaseModel data
          ) -> void

        def to_hash: -> Increase::Models::CardPurchaseSupplementListParams::created_at
      end
    end
  end
end
