module Increase
  module Models
    type check_deposit_retrieve_params = {  } & Increase::request_parameters

    class CheckDepositRetrieveParams < Increase::BaseModel
      extend Increase::Type::RequestParameters::Converter
      include Increase::RequestParameters

      def initialize: (?request_options: Increase::request_opts) -> void

      def to_hash: -> Increase::Models::check_deposit_retrieve_params
    end
  end
end
