module Increase
  module Models
    type check_transfer_stop_payment_params =
      { reason: Increase::Models::CheckTransferStopPaymentParams::reason }
      & Increase::Internal::Type::request_parameters

    class CheckTransferStopPaymentParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_reader reason: Increase::Models::CheckTransferStopPaymentParams::reason?

      def reason=: (
        Increase::Models::CheckTransferStopPaymentParams::reason
      ) -> Increase::Models::CheckTransferStopPaymentParams::reason

      def initialize: (
        ?reason: Increase::Models::CheckTransferStopPaymentParams::reason,
        ?request_options: Increase::request_opts
      ) -> void

      type reason = :mail_delivery_failed | :not_authorized | :unknown

      module Reason
        extend Increase::Internal::Type::Enum

        # The check could not be delivered.
        MAIL_DELIVERY_FAILED: :mail_delivery_failed

        # The check was not authorized.
        NOT_AUTHORIZED: :not_authorized

        # The check was stopped for another reason.
        UNKNOWN: :unknown

        def self?.values: -> ::Array[Increase::Models::CheckTransferStopPaymentParams::reason]
      end
    end
  end
end
