module Increase
  module Models
    type check_transfer_retrieve_params = {  } & Increase::request_parameters

    class CheckTransferRetrieveParams < Increase::BaseModel
      extend Increase::RequestParameters::Converter
      include Increase::RequestParameters

      def initialize: (?request_options: Increase::request_opts) -> void

      def to_hash: -> Increase::Models::check_transfer_retrieve_params
    end
  end
end
