module Increase
  module Models
    type check_deposit_retrieve_params =
      {  } & Increase::Internal::Type::request_parameters

    class CheckDepositRetrieveParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      def initialize: (?request_options: Increase::request_opts) -> void

      def to_hash: -> Increase::Models::check_deposit_retrieve_params
    end
  end
end
