module Increase
  module Models
    type check_deposit_create_params =
      {
        account_id: String,
        amount: Integer,
        back_image_file_id: String,
        front_image_file_id: String,
        description: String
      }
      & Increase::Internal::Type::request_parameters

    class CheckDepositCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor account_id: String

      attr_accessor amount: Integer

      attr_accessor back_image_file_id: String

      attr_accessor front_image_file_id: String

      attr_reader description: String?

      def description=: (String) -> String

      def initialize: (
        account_id: String,
        amount: Integer,
        back_image_file_id: String,
        front_image_file_id: String,
        ?description: String,
        ?request_options: Increase::request_opts
      ) -> void
    end
  end
end
