module Increase
  module Models
    type declined_transaction_retrieve_params =
      {  } & Increase::request_parameters

    class DeclinedTransactionRetrieveParams < Increase::BaseModel
      extend Increase::RequestParameters::Converter
      include Increase::RequestParameters

      def initialize: (?request_options: Increase::request_opts) -> void

      def to_hash: -> Increase::Models::declined_transaction_retrieve_params
    end
  end
end
