module Increase
  module Models
    type digital_card_profile_create_params =
      {
        app_icon_file_id: String,
        background_image_file_id: String,
        card_description: String,
        description: String,
        issuer_name: String,
        contact_email: String,
        contact_phone: String,
        contact_website: String,
        text_color: Increase::DigitalCardProfileCreateParams::TextColor
      }
      & Increase::Internal::Type::request_parameters

    class DigitalCardProfileCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor app_icon_file_id: String

      attr_accessor background_image_file_id: String

      attr_accessor card_description: String

      attr_accessor description: String

      attr_accessor issuer_name: String

      attr_reader contact_email: String?

      def contact_email=: (String) -> String

      attr_reader contact_phone: String?

      def contact_phone=: (String) -> String

      attr_reader contact_website: String?

      def contact_website=: (String) -> String

      attr_reader text_color: Increase::DigitalCardProfileCreateParams::TextColor?

      def text_color=: (
        Increase::DigitalCardProfileCreateParams::TextColor
      ) -> Increase::DigitalCardProfileCreateParams::TextColor

      def initialize: (
        app_icon_file_id: String,
        background_image_file_id: String,
        card_description: String,
        description: String,
        issuer_name: String,
        ?contact_email: String,
        ?contact_phone: String,
        ?contact_website: String,
        ?text_color: Increase::DigitalCardProfileCreateParams::TextColor,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        app_icon_file_id: String,
        background_image_file_id: String,
        card_description: String,
        description: String,
        issuer_name: String,
        contact_email: String,
        contact_phone: String,
        contact_website: String,
        text_color: Increase::DigitalCardProfileCreateParams::TextColor,
        request_options: Increase::RequestOptions
      }

      type text_color = { blue: Integer, green: Integer, red: Integer }

      class TextColor < Increase::Internal::Type::BaseModel
        attr_accessor blue: Integer

        attr_accessor green: Integer

        attr_accessor red: Integer

        def initialize: (blue: Integer, green: Integer, red: Integer) -> void

        def to_hash: -> { blue: Integer, green: Integer, red: Integer }
      end
    end
  end
end
