module Increase
  module Models
    type digital_card_profile_retrieve_params =
      {  } & Increase::Internal::Type::request_parameters

    class DigitalCardProfileRetrieveParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      def initialize: (?request_options: Increase::request_opts) -> void
    end
  end
end
