module Increase
  module Models
    type digital_card_profile_list_params =
      {
        cursor: String,
        idempotency_key: String,
        limit: Integer,
        status: Increase::DigitalCardProfileListParams::Status
      }
      & Increase::Internal::Type::request_parameters

    class DigitalCardProfileListParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader status: Increase::DigitalCardProfileListParams::Status?

      def status=: (
        Increase::DigitalCardProfileListParams::Status
      ) -> Increase::DigitalCardProfileListParams::Status

      def initialize: (
        ?cursor: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?status: Increase::DigitalCardProfileListParams::Status,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        cursor: String,
        idempotency_key: String,
        limit: Integer,
        status: Increase::DigitalCardProfileListParams::Status,
        request_options: Increase::RequestOptions
      }

      type status =
        {
          in_: ::Array[Increase::Models::DigitalCardProfileListParams::Status::in_]
        }

      class Status < Increase::Internal::Type::BaseModel
        attr_reader in_: ::Array[Increase::Models::DigitalCardProfileListParams::Status::in_]?

        def in_=: (
          ::Array[Increase::Models::DigitalCardProfileListParams::Status::in_]
        ) -> ::Array[Increase::Models::DigitalCardProfileListParams::Status::in_]

        def initialize: (
          ?in_: ::Array[Increase::Models::DigitalCardProfileListParams::Status::in_]
        ) -> void

        def to_hash: -> {
          in_: ::Array[Increase::Models::DigitalCardProfileListParams::Status::in_]
        }

        type in_ = :pending | :rejected | :active | :archived

        module In
          extend Increase::Internal::Type::Enum

          # The Card Profile is awaiting review from Increase and/or processing by card networks.
          PENDING: :pending

          # There is an issue with the Card Profile preventing it from use.
          REJECTED: :rejected

          # The Card Profile can be assigned to Cards.
          ACTIVE: :active

          # The Card Profile is no longer in use.
          ARCHIVED: :archived

          def self?.values: -> ::Array[Increase::Models::DigitalCardProfileListParams::Status::in_]
        end
      end
    end
  end
end
