module Increase
  module Models
    type digital_card_profile_retrieve_params =
      {  } & Increase::request_parameters

    class DigitalCardProfileRetrieveParams < Increase::BaseModel
      extend Increase::Type::RequestParameters::Converter
      include Increase::RequestParameters

      def initialize: (?request_options: Increase::request_opts) -> void

      def to_hash: -> Increase::Models::digital_card_profile_retrieve_params
    end
  end
end
