module Increase
  module Models
    type digital_wallet_token =
      {
        id: String,
        card_id: String,
        cardholder: Increase::Models::DigitalWalletToken::Cardholder,
        created_at: Time,
        device: Increase::Models::DigitalWalletToken::Device,
        status: Increase::Models::DigitalWalletToken::status,
        token_requestor: Increase::Models::DigitalWalletToken::token_requestor,
        type: Increase::Models::DigitalWalletToken::type_,
        updates: ::Array[Increase::Models::DigitalWalletToken::Update]
      }

    class DigitalWalletToken < Increase::BaseModel
      attr_accessor id: String

      attr_accessor card_id: String

      attr_accessor cardholder: Increase::Models::DigitalWalletToken::Cardholder

      attr_accessor created_at: Time

      attr_accessor device: Increase::Models::DigitalWalletToken::Device

      attr_accessor status: Increase::Models::DigitalWalletToken::status

      attr_accessor token_requestor: Increase::Models::DigitalWalletToken::token_requestor

      attr_accessor type: Increase::Models::DigitalWalletToken::type_

      attr_accessor updates: ::Array[Increase::Models::DigitalWalletToken::Update]

      def initialize: (
        id: String,
        card_id: String,
        cardholder: Increase::Models::DigitalWalletToken::Cardholder,
        created_at: Time,
        device: Increase::Models::DigitalWalletToken::Device,
        status: Increase::Models::DigitalWalletToken::status,
        token_requestor: Increase::Models::DigitalWalletToken::token_requestor,
        type: Increase::Models::DigitalWalletToken::type_,
        updates: ::Array[Increase::Models::DigitalWalletToken::Update]
      ) -> void

      def to_hash: -> Increase::Models::digital_wallet_token

      type cardholder = { name: String? }

      class Cardholder < Increase::BaseModel
        attr_accessor name: String?

        def initialize: (name: String?) -> void

        def to_hash: -> Increase::Models::DigitalWalletToken::cardholder
      end

      type device =
        {
          device_type: Increase::Models::DigitalWalletToken::Device::device_type?,
          identifier: String?,
          ip_address: String?,
          name: String?
        }

      class Device < Increase::BaseModel
        attr_accessor device_type: Increase::Models::DigitalWalletToken::Device::device_type?

        attr_accessor identifier: String?

        attr_accessor ip_address: String?

        attr_accessor name: String?

        def initialize: (
          device_type: Increase::Models::DigitalWalletToken::Device::device_type?,
          identifier: String?,
          ip_address: String?,
          name: String?
        ) -> void

        def to_hash: -> Increase::Models::DigitalWalletToken::device

        type device_type =
          :unknown
          | :mobile_phone
          | :tablet
          | :watch
          | :mobilephone_or_tablet
          | :pc
          | :household_device
          | :wearable_device
          | :automobile_device

        module DeviceType
          extend Increase::Enum

          # Unknown
          UNKNOWN: :unknown

          # Mobile Phone
          MOBILE_PHONE: :mobile_phone

          # Tablet
          TABLET: :tablet

          # Watch
          WATCH: :watch

          # Mobile Phone or Tablet
          MOBILEPHONE_OR_TABLET: :mobilephone_or_tablet

          # PC
          PC: :pc

          # Household Device
          HOUSEHOLD_DEVICE: :household_device

          # Wearable Device
          WEARABLE_DEVICE: :wearable_device

          # Automobile Device
          AUTOMOBILE_DEVICE: :automobile_device

          def self?.values: -> ::Array[Increase::Models::DigitalWalletToken::Device::device_type]
        end
      end

      type status = :active | :inactive | :suspended | :deactivated

      module Status
        extend Increase::Enum

        # The digital wallet token is active.
        ACTIVE: :active

        # The digital wallet token has been created but not successfully activated via two-factor authentication yet.
        INACTIVE: :inactive

        # The digital wallet token has been temporarily paused.
        SUSPENDED: :suspended

        # The digital wallet token has been permanently canceled.
        DEACTIVATED: :deactivated

        def self?.values: -> ::Array[Increase::Models::DigitalWalletToken::status]
      end

      type token_requestor = :apple_pay | :google_pay | :samsung_pay | :unknown

      module TokenRequestor
        extend Increase::Enum

        # Apple Pay
        APPLE_PAY: :apple_pay

        # Google Pay
        GOOGLE_PAY: :google_pay

        # Samsung Pay
        SAMSUNG_PAY: :samsung_pay

        # Unknown
        UNKNOWN: :unknown

        def self?.values: -> ::Array[Increase::Models::DigitalWalletToken::token_requestor]
      end

      type type_ = :digital_wallet_token

      module Type
        extend Increase::Enum

        DIGITAL_WALLET_TOKEN: :digital_wallet_token

        def self?.values: -> ::Array[Increase::Models::DigitalWalletToken::type_]
      end

      type update =
        {
          status: Increase::Models::DigitalWalletToken::Update::status,
          timestamp: Time
        }

      class Update < Increase::BaseModel
        attr_accessor status: Increase::Models::DigitalWalletToken::Update::status

        attr_accessor timestamp: Time

        def initialize: (
          status: Increase::Models::DigitalWalletToken::Update::status,
          timestamp: Time
        ) -> void

        def to_hash: -> Increase::Models::DigitalWalletToken::update

        type status = :active | :inactive | :suspended | :deactivated

        module Status
          extend Increase::Enum

          # The digital wallet token is active.
          ACTIVE: :active

          # The digital wallet token has been created but not successfully activated via two-factor authentication yet.
          INACTIVE: :inactive

          # The digital wallet token has been temporarily paused.
          SUSPENDED: :suspended

          # The digital wallet token has been permanently canceled.
          DEACTIVATED: :deactivated

          def self?.values: -> ::Array[Increase::Models::DigitalWalletToken::Update::status]
        end
      end
    end
  end
end
