module Increase
  module Models
    type digital_card_profile_clone_params =
      {
        app_icon_file_id: String,
        background_image_file_id: String,
        card_description: String,
        contact_email: String,
        contact_phone: String,
        contact_website: String,
        description: String,
        issuer_name: String,
        text_color: Increase::DigitalCardProfileCloneParams::TextColor
      }
      & Increase::Internal::Type::request_parameters

    class DigitalCardProfileCloneParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_reader app_icon_file_id: String?

      def app_icon_file_id=: (String) -> String

      attr_reader background_image_file_id: String?

      def background_image_file_id=: (String) -> String

      attr_reader card_description: String?

      def card_description=: (String) -> String

      attr_reader contact_email: String?

      def contact_email=: (String) -> String

      attr_reader contact_phone: String?

      def contact_phone=: (String) -> String

      attr_reader contact_website: String?

      def contact_website=: (String) -> String

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader issuer_name: String?

      def issuer_name=: (String) -> String

      attr_reader text_color: Increase::DigitalCardProfileCloneParams::TextColor?

      def text_color=: (
        Increase::DigitalCardProfileCloneParams::TextColor
      ) -> Increase::DigitalCardProfileCloneParams::TextColor

      def initialize: (
        ?app_icon_file_id: String,
        ?background_image_file_id: String,
        ?card_description: String,
        ?contact_email: String,
        ?contact_phone: String,
        ?contact_website: String,
        ?description: String,
        ?issuer_name: String,
        ?text_color: Increase::DigitalCardProfileCloneParams::TextColor,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        app_icon_file_id: String,
        background_image_file_id: String,
        card_description: String,
        contact_email: String,
        contact_phone: String,
        contact_website: String,
        description: String,
        issuer_name: String,
        text_color: Increase::DigitalCardProfileCloneParams::TextColor,
        request_options: Increase::RequestOptions
      }

      type text_color = { blue: Integer, green: Integer, red: Integer }

      class TextColor < Increase::Internal::Type::BaseModel
        attr_accessor blue: Integer

        attr_accessor green: Integer

        attr_accessor red: Integer

        def initialize: (blue: Integer, green: Integer, red: Integer) -> void

        def to_hash: -> { blue: Integer, green: Integer, red: Integer }
      end
    end
  end
end
