module Increase
  module Models
    type document =
      {
        id: String,
        category: Increase::Models::Document::category,
        created_at: Time,
        entity_id: String?,
        file_id: String,
        type: Increase::Models::Document::type_
      }

    class Document < Increase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor category: Increase::Models::Document::category

      attr_accessor created_at: Time

      attr_accessor entity_id: String?

      attr_accessor file_id: String

      attr_accessor type: Increase::Models::Document::type_

      def initialize: (
        id: String,
        category: Increase::Models::Document::category,
        created_at: Time,
        entity_id: String?,
        file_id: String,
        type: Increase::Models::Document::type_
      ) -> void

      def to_hash: -> {
        id: String,
        category: Increase::Models::Document::category,
        created_at: Time,
        entity_id: String?,
        file_id: String,
        type: Increase::Models::Document::type_
      }

      type category =
        :form_1099_int
        | :form_1099_misc
        | :proof_of_authorization
        | :company_information

      module Category
        extend Increase::Internal::Type::Enum

        # Internal Revenue Service Form 1099-INT.
        FORM_1099_INT: :form_1099_int

        # Internal Revenue Service Form 1099-MISC.
        FORM_1099_MISC: :form_1099_misc

        # A document submitted in response to a proof of authorization request for an ACH transfer.
        PROOF_OF_AUTHORIZATION: :proof_of_authorization

        # Company information, such a policies or procedures, typically submitted during our due diligence process.
        COMPANY_INFORMATION: :company_information

        def self?.values: -> ::Array[Increase::Models::Document::category]
      end

      type type_ = :document

      module Type
        extend Increase::Internal::Type::Enum

        DOCUMENT: :document

        def self?.values: -> ::Array[Increase::Models::Document::type_]
      end
    end
  end
end
