module Increase
  module Models
    type entity_create_beneficial_owner_params =
      {
        beneficial_owner: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner
      }
      & Increase::Internal::Type::request_parameters

    class EntityCreateBeneficialOwnerParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor beneficial_owner: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner

      def initialize: (
        beneficial_owner: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        beneficial_owner: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner,
        request_options: Increase::RequestOptions
      }

      type beneficial_owner =
        {
          individual: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual,
          prongs: ::Array[Increase::Models::EntityCreateBeneficialOwnerParams::BeneficialOwner::prong],
          company_title: String
        }

      class BeneficialOwner < Increase::Internal::Type::BaseModel
        attr_accessor individual: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual

        attr_accessor prongs: ::Array[Increase::Models::EntityCreateBeneficialOwnerParams::BeneficialOwner::prong]

        attr_reader company_title: String?

        def company_title=: (String) -> String

        def initialize: (
          individual: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual,
          prongs: ::Array[Increase::Models::EntityCreateBeneficialOwnerParams::BeneficialOwner::prong],
          ?company_title: String
        ) -> void

        def to_hash: -> {
          individual: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual,
          prongs: ::Array[Increase::Models::EntityCreateBeneficialOwnerParams::BeneficialOwner::prong],
          company_title: String
        }

        type individual =
          {
            address: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Address,
            date_of_birth: Date,
            identification: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification,
            name: String,
            confirmed_no_us_tax_id: bool
          }

        class Individual < Increase::Internal::Type::BaseModel
          attr_accessor address: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Address

          attr_accessor date_of_birth: Date

          attr_accessor identification: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification

          attr_accessor name: String

          attr_reader confirmed_no_us_tax_id: bool?

          def confirmed_no_us_tax_id=: (bool) -> bool

          def initialize: (
            address: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Address,
            date_of_birth: Date,
            identification: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification,
            name: String,
            ?confirmed_no_us_tax_id: bool
          ) -> void

          def to_hash: -> {
            address: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Address,
            date_of_birth: Date,
            identification: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification,
            name: String,
            confirmed_no_us_tax_id: bool
          }

          type address =
            {
              country: String,
              :line1 => String,
              city: String,
              :line2 => String,
              state: String,
              zip: String
            }

          class Address < Increase::Internal::Type::BaseModel
            attr_accessor country: String

            attr_accessor line1: String

            attr_reader city: String?

            def city=: (String) -> String

            attr_reader line2: String?

            def line2=: (String) -> String

            attr_reader state: String?

            def state=: (String) -> String

            attr_reader zip: String?

            def zip=: (String) -> String

            def initialize: (
              country: String,
              line1: String,
              ?city: String,
              ?line2: String,
              ?state: String,
              ?zip: String
            ) -> void

            def to_hash: -> {
              country: String,
              :line1 => String,
              city: String,
              :line2 => String,
              state: String,
              zip: String
            }
          end

          type identification =
            {
              method_: Increase::Models::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::method_,
              number: String,
              drivers_license: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::DriversLicense,
              other: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::Other,
              passport: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::Passport
            }

          class Identification < Increase::Internal::Type::BaseModel
            attr_accessor method_: Increase::Models::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::method_

            attr_accessor number: String

            attr_reader drivers_license: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::DriversLicense?

            def drivers_license=: (
              Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::DriversLicense
            ) -> Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::DriversLicense

            attr_reader other: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::Other?

            def other=: (
              Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::Other
            ) -> Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::Other

            attr_reader passport: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::Passport?

            def passport=: (
              Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::Passport
            ) -> Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::Passport

            def initialize: (
              method_: Increase::Models::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::method_,
              number: String,
              ?drivers_license: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::DriversLicense,
              ?other: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::Other,
              ?passport: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::Passport
            ) -> void

            def to_hash: -> {
              method_: Increase::Models::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::method_,
              number: String,
              drivers_license: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::DriversLicense,
              other: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::Other,
              passport: Increase::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::Passport
            }

            type method_ =
              :social_security_number
              | :individual_taxpayer_identification_number
              | :passport
              | :drivers_license
              | :other

            module Method
              extend Increase::Internal::Type::Enum

              # A social security number.
              SOCIAL_SECURITY_NUMBER: :social_security_number

              # An individual taxpayer identification number (ITIN).
              INDIVIDUAL_TAXPAYER_IDENTIFICATION_NUMBER: :individual_taxpayer_identification_number

              # A passport number.
              PASSPORT: :passport

              # A driver's license number.
              DRIVERS_LICENSE: :drivers_license

              # Another identifying document.
              OTHER: :other

              def self?.values: -> ::Array[Increase::Models::EntityCreateBeneficialOwnerParams::BeneficialOwner::Individual::Identification::method_]
            end

            type drivers_license =
              {
                expiration_date: Date,
                file_id: String,
                state: String,
                back_file_id: String
              }

            class DriversLicense < Increase::Internal::Type::BaseModel
              attr_accessor expiration_date: Date

              attr_accessor file_id: String

              attr_accessor state: String

              attr_reader back_file_id: String?

              def back_file_id=: (String) -> String

              def initialize: (
                expiration_date: Date,
                file_id: String,
                state: String,
                ?back_file_id: String
              ) -> void

              def to_hash: -> {
                expiration_date: Date,
                file_id: String,
                state: String,
                back_file_id: String
              }
            end

            type other =
              {
                country: String,
                description: String,
                file_id: String,
                back_file_id: String,
                expiration_date: Date
              }

            class Other < Increase::Internal::Type::BaseModel
              attr_accessor country: String

              attr_accessor description: String

              attr_accessor file_id: String

              attr_reader back_file_id: String?

              def back_file_id=: (String) -> String

              attr_reader expiration_date: Date?

              def expiration_date=: (Date) -> Date

              def initialize: (
                country: String,
                description: String,
                file_id: String,
                ?back_file_id: String,
                ?expiration_date: Date
              ) -> void

              def to_hash: -> {
                country: String,
                description: String,
                file_id: String,
                back_file_id: String,
                expiration_date: Date
              }
            end

            type passport =
              { country: String, expiration_date: Date, file_id: String }

            class Passport < Increase::Internal::Type::BaseModel
              attr_accessor country: String

              attr_accessor expiration_date: Date

              attr_accessor file_id: String

              def initialize: (
                country: String,
                expiration_date: Date,
                file_id: String
              ) -> void

              def to_hash: -> {
                country: String,
                expiration_date: Date,
                file_id: String
              }
            end
          end
        end

        type prong = :ownership | :control

        module Prong
          extend Increase::Internal::Type::Enum

          # A person with 25% or greater direct or indirect ownership of the entity.
          OWNERSHIP: :ownership

          # A person who manages, directs, or has significant control of the entity.
          CONTROL: :control

          def self?.values: -> ::Array[Increase::Models::EntityCreateBeneficialOwnerParams::BeneficialOwner::prong]
        end
      end
    end
  end
end
