module Increase
  module Models
    type entity_supplemental_document =
      {
        created_at: Time,
        entity_id: String,
        file_id: String,
        idempotency_key: String?,
        type: Increase::Models::EntitySupplementalDocument::type_
      }

    class EntitySupplementalDocument < Increase::Internal::Type::BaseModel
      attr_accessor created_at: Time

      attr_accessor entity_id: String

      attr_accessor file_id: String

      attr_accessor idempotency_key: String?

      attr_accessor type: Increase::Models::EntitySupplementalDocument::type_

      def initialize: (
        created_at: Time,
        entity_id: String,
        file_id: String,
        idempotency_key: String?,
        type: Increase::Models::EntitySupplementalDocument::type_
      ) -> void

      def to_hash: -> {
        created_at: Time,
        entity_id: String,
        file_id: String,
        idempotency_key: String?,
        type: Increase::Models::EntitySupplementalDocument::type_
      }

      type type_ = :entity_supplemental_document

      module Type
        extend Increase::Internal::Type::Enum

        ENTITY_SUPPLEMENTAL_DOCUMENT: :entity_supplemental_document

        def self?.values: -> ::Array[Increase::Models::EntitySupplementalDocument::type_]
      end
    end
  end
end
