module Increase
  module Models
    type entity_update_beneficial_owner_address_params =
      {
        address: Increase::EntityUpdateBeneficialOwnerAddressParams::Address,
        beneficial_owner_id: String
      }
      & Increase::Internal::Type::request_parameters

    class EntityUpdateBeneficialOwnerAddressParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor address: Increase::EntityUpdateBeneficialOwnerAddressParams::Address

      attr_accessor beneficial_owner_id: String

      def initialize: (
        address: Increase::EntityUpdateBeneficialOwnerAddressParams::Address,
        beneficial_owner_id: String,
        ?request_options: Increase::request_opts
      ) -> void

      type address =
        {
          country: String,
          :line1 => String,
          city: String,
          :line2 => String,
          state: String,
          zip: String
        }

      class Address < Increase::Internal::Type::BaseModel
        attr_accessor country: String

        attr_accessor line1: String

        attr_reader city: String?

        def city=: (String) -> String

        attr_reader line2: String?

        def line2=: (String) -> String

        attr_reader state: String?

        def state=: (String) -> String

        attr_reader zip: String?

        def zip=: (String) -> String

        def initialize: (
          country: String,
          line1: String,
          ?city: String,
          ?line2: String,
          ?state: String,
          ?zip: String
        ) -> void
      end
    end
  end
end
