module Increase
  module Models
    type entity_update_address_params =
      { address: Increase::EntityUpdateAddressParams::Address }
      & Increase::Internal::Type::request_parameters

    class EntityUpdateAddressParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor address: Increase::EntityUpdateAddressParams::Address

      def initialize: (
        address: Increase::EntityUpdateAddressParams::Address,
        ?request_options: Increase::request_opts
      ) -> void

      type address =
        {
          city: String,
          :line1 => String,
          state: String,
          zip: String,
          :line2 => String
        }

      class Address < Increase::Internal::Type::BaseModel
        attr_accessor city: String

        attr_accessor line1: String

        attr_accessor state: String

        attr_accessor zip: String

        attr_reader line2: String?

        def line2=: (String) -> String

        def initialize: (
          city: String,
          line1: String,
          state: String,
          zip: String,
          ?line2: String
        ) -> void
      end
    end
  end
end
