module Increase
  module Models
    type entity_update_industry_code_params =
      { industry_code: String } & Increase::Internal::Type::request_parameters

    class EntityUpdateIndustryCodeParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor industry_code: String

      def initialize: (
        industry_code: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        industry_code: String,
        request_options: Increase::RequestOptions
      }
    end
  end
end
