module Increase
  module Models
    type event_retrieve_params = {  } & Increase::request_parameters

    class EventRetrieveParams < Increase::BaseModel
      extend Increase::RequestParameters::Converter
      include Increase::RequestParameters

      def initialize:
        (?request_options: Increase::request_opts) -> void
        | (
          ?Increase::Models::event_retrieve_params | Increase::BaseModel data
        ) -> void

      def to_hash: -> Increase::Models::event_retrieve_params
    end
  end
end
