module Increase
  module Models
    type event_subscription_update_params =
      { status: Increase::Models::EventSubscriptionUpdateParams::status }
      & Increase::Internal::Type::request_parameters

    class EventSubscriptionUpdateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_reader status: Increase::Models::EventSubscriptionUpdateParams::status?

      def status=: (
        Increase::Models::EventSubscriptionUpdateParams::status
      ) -> Increase::Models::EventSubscriptionUpdateParams::status

      def initialize: (
        ?status: Increase::Models::EventSubscriptionUpdateParams::status,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> Increase::Models::event_subscription_update_params

      type status = :active | :disabled | :deleted

      module Status
        extend Increase::Internal::Type::Enum

        # The subscription is active and Events will be delivered normally.
        ACTIVE: :active

        # The subscription is temporarily disabled and Events will not be delivered.
        DISABLED: :disabled

        # The subscription is permanently disabled and Events will not be delivered.
        DELETED: :deleted

        def self?.values: -> ::Array[Increase::Models::EventSubscriptionUpdateParams::status]
      end
    end
  end
end
