module Increase
  module Models
    type event_subscription_list_params =
      { cursor: String, idempotency_key: String, limit: Integer }
      & Increase::Internal::Type::request_parameters

    class EventSubscriptionListParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      def initialize: (
        ?cursor: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        cursor: String,
        idempotency_key: String,
        limit: Integer,
        request_options: Increase::RequestOptions
      }
    end
  end
end
