module Increase
  module Models
    type export_create_params =
      {
        category: Increase::Models::ExportCreateParams::category,
        account_statement_ofx: Increase::ExportCreateParams::AccountStatementOfx,
        balance_csv: Increase::ExportCreateParams::BalanceCsv,
        bookkeeping_account_balance_csv: Increase::ExportCreateParams::BookkeepingAccountBalanceCsv,
        entity_csv: Increase::ExportCreateParams::EntityCsv,
        transaction_csv: Increase::ExportCreateParams::TransactionCsv,
        vendor_csv: top
      }
      & Increase::Internal::Type::request_parameters

    class ExportCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor category: Increase::Models::ExportCreateParams::category

      attr_reader account_statement_ofx: Increase::ExportCreateParams::AccountStatementOfx?

      def account_statement_ofx=: (
        Increase::ExportCreateParams::AccountStatementOfx
      ) -> Increase::ExportCreateParams::AccountStatementOfx

      attr_reader balance_csv: Increase::ExportCreateParams::BalanceCsv?

      def balance_csv=: (
        Increase::ExportCreateParams::BalanceCsv
      ) -> Increase::ExportCreateParams::BalanceCsv

      attr_reader bookkeeping_account_balance_csv: Increase::ExportCreateParams::BookkeepingAccountBalanceCsv?

      def bookkeeping_account_balance_csv=: (
        Increase::ExportCreateParams::BookkeepingAccountBalanceCsv
      ) -> Increase::ExportCreateParams::BookkeepingAccountBalanceCsv

      attr_reader entity_csv: Increase::ExportCreateParams::EntityCsv?

      def entity_csv=: (
        Increase::ExportCreateParams::EntityCsv
      ) -> Increase::ExportCreateParams::EntityCsv

      attr_reader transaction_csv: Increase::ExportCreateParams::TransactionCsv?

      def transaction_csv=: (
        Increase::ExportCreateParams::TransactionCsv
      ) -> Increase::ExportCreateParams::TransactionCsv

      attr_reader vendor_csv: top?

      def vendor_csv=: (top) -> top

      def initialize: (
        category: Increase::Models::ExportCreateParams::category,
        ?account_statement_ofx: Increase::ExportCreateParams::AccountStatementOfx,
        ?balance_csv: Increase::ExportCreateParams::BalanceCsv,
        ?bookkeeping_account_balance_csv: Increase::ExportCreateParams::BookkeepingAccountBalanceCsv,
        ?entity_csv: Increase::ExportCreateParams::EntityCsv,
        ?transaction_csv: Increase::ExportCreateParams::TransactionCsv,
        ?vendor_csv: top,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        category: Increase::Models::ExportCreateParams::category,
        account_statement_ofx: Increase::ExportCreateParams::AccountStatementOfx,
        balance_csv: Increase::ExportCreateParams::BalanceCsv,
        bookkeeping_account_balance_csv: Increase::ExportCreateParams::BookkeepingAccountBalanceCsv,
        entity_csv: Increase::ExportCreateParams::EntityCsv,
        transaction_csv: Increase::ExportCreateParams::TransactionCsv,
        vendor_csv: top,
        request_options: Increase::RequestOptions
      }

      type category =
        :account_statement_ofx
        | :transaction_csv
        | :balance_csv
        | :bookkeeping_account_balance_csv
        | :entity_csv
        | :vendor_csv

      module Category
        extend Increase::Internal::Type::Enum

        # Export an Open Financial Exchange (OFX) file of transactions and balances for a given time range and Account.
        ACCOUNT_STATEMENT_OFX: :account_statement_ofx

        # Export a CSV of all transactions for a given time range.
        TRANSACTION_CSV: :transaction_csv

        # Export a CSV of account balances for the dates in a given range.
        BALANCE_CSV: :balance_csv

        # Export a CSV of bookkeeping account balances for the dates in a given range.
        BOOKKEEPING_ACCOUNT_BALANCE_CSV: :bookkeeping_account_balance_csv

        # Export a CSV of entities with a given status.
        ENTITY_CSV: :entity_csv

        # Export a CSV of vendors added to the third-party risk management dashboard.
        VENDOR_CSV: :vendor_csv

        def self?.values: -> ::Array[Increase::Models::ExportCreateParams::category]
      end

      type account_statement_ofx =
        {
          account_id: String,
          created_at: Increase::ExportCreateParams::AccountStatementOfx::CreatedAt
        }

      class AccountStatementOfx < Increase::Internal::Type::BaseModel
        attr_accessor account_id: String

        attr_reader created_at: Increase::ExportCreateParams::AccountStatementOfx::CreatedAt?

        def created_at=: (
          Increase::ExportCreateParams::AccountStatementOfx::CreatedAt
        ) -> Increase::ExportCreateParams::AccountStatementOfx::CreatedAt

        def initialize: (
          account_id: String,
          ?created_at: Increase::ExportCreateParams::AccountStatementOfx::CreatedAt
        ) -> void

        def to_hash: -> {
          account_id: String,
          created_at: Increase::ExportCreateParams::AccountStatementOfx::CreatedAt
        }

        type created_at =
          { after: Time, before: Time, on_or_after: Time, on_or_before: Time }

        class CreatedAt < Increase::Internal::Type::BaseModel
          attr_reader after: Time?

          def after=: (Time) -> Time

          attr_reader before: Time?

          def before=: (Time) -> Time

          attr_reader on_or_after: Time?

          def on_or_after=: (Time) -> Time

          attr_reader on_or_before: Time?

          def on_or_before=: (Time) -> Time

          def initialize: (
            ?after: Time,
            ?before: Time,
            ?on_or_after: Time,
            ?on_or_before: Time
          ) -> void

          def to_hash: -> {
            after: Time,
            before: Time,
            on_or_after: Time,
            on_or_before: Time
          }
        end
      end

      type balance_csv =
        {
          account_id: String,
          created_at: Increase::ExportCreateParams::BalanceCsv::CreatedAt,
          program_id: String
        }

      class BalanceCsv < Increase::Internal::Type::BaseModel
        attr_reader account_id: String?

        def account_id=: (String) -> String

        attr_reader created_at: Increase::ExportCreateParams::BalanceCsv::CreatedAt?

        def created_at=: (
          Increase::ExportCreateParams::BalanceCsv::CreatedAt
        ) -> Increase::ExportCreateParams::BalanceCsv::CreatedAt

        attr_reader program_id: String?

        def program_id=: (String) -> String

        def initialize: (
          ?account_id: String,
          ?created_at: Increase::ExportCreateParams::BalanceCsv::CreatedAt,
          ?program_id: String
        ) -> void

        def to_hash: -> {
          account_id: String,
          created_at: Increase::ExportCreateParams::BalanceCsv::CreatedAt,
          program_id: String
        }

        type created_at =
          { after: Time, before: Time, on_or_after: Time, on_or_before: Time }

        class CreatedAt < Increase::Internal::Type::BaseModel
          attr_reader after: Time?

          def after=: (Time) -> Time

          attr_reader before: Time?

          def before=: (Time) -> Time

          attr_reader on_or_after: Time?

          def on_or_after=: (Time) -> Time

          attr_reader on_or_before: Time?

          def on_or_before=: (Time) -> Time

          def initialize: (
            ?after: Time,
            ?before: Time,
            ?on_or_after: Time,
            ?on_or_before: Time
          ) -> void

          def to_hash: -> {
            after: Time,
            before: Time,
            on_or_after: Time,
            on_or_before: Time
          }
        end
      end

      type bookkeeping_account_balance_csv =
        {
          bookkeeping_account_id: String,
          created_at: Increase::ExportCreateParams::BookkeepingAccountBalanceCsv::CreatedAt
        }

      class BookkeepingAccountBalanceCsv < Increase::Internal::Type::BaseModel
        attr_reader bookkeeping_account_id: String?

        def bookkeeping_account_id=: (String) -> String

        attr_reader created_at: Increase::ExportCreateParams::BookkeepingAccountBalanceCsv::CreatedAt?

        def created_at=: (
          Increase::ExportCreateParams::BookkeepingAccountBalanceCsv::CreatedAt
        ) -> Increase::ExportCreateParams::BookkeepingAccountBalanceCsv::CreatedAt

        def initialize: (
          ?bookkeeping_account_id: String,
          ?created_at: Increase::ExportCreateParams::BookkeepingAccountBalanceCsv::CreatedAt
        ) -> void

        def to_hash: -> {
          bookkeeping_account_id: String,
          created_at: Increase::ExportCreateParams::BookkeepingAccountBalanceCsv::CreatedAt
        }

        type created_at =
          { after: Time, before: Time, on_or_after: Time, on_or_before: Time }

        class CreatedAt < Increase::Internal::Type::BaseModel
          attr_reader after: Time?

          def after=: (Time) -> Time

          attr_reader before: Time?

          def before=: (Time) -> Time

          attr_reader on_or_after: Time?

          def on_or_after=: (Time) -> Time

          attr_reader on_or_before: Time?

          def on_or_before=: (Time) -> Time

          def initialize: (
            ?after: Time,
            ?before: Time,
            ?on_or_after: Time,
            ?on_or_before: Time
          ) -> void

          def to_hash: -> {
            after: Time,
            before: Time,
            on_or_after: Time,
            on_or_before: Time
          }
        end
      end

      type entity_csv =
        { status: Increase::ExportCreateParams::EntityCsv::Status }

      class EntityCsv < Increase::Internal::Type::BaseModel
        attr_reader status: Increase::ExportCreateParams::EntityCsv::Status?

        def status=: (
          Increase::ExportCreateParams::EntityCsv::Status
        ) -> Increase::ExportCreateParams::EntityCsv::Status

        def initialize: (
          ?status: Increase::ExportCreateParams::EntityCsv::Status
        ) -> void

        def to_hash: -> {
          status: Increase::ExportCreateParams::EntityCsv::Status
        }

        type status =
          {
            in_: ::Array[Increase::Models::ExportCreateParams::EntityCsv::Status::in_]
          }

        class Status < Increase::Internal::Type::BaseModel
          attr_accessor in_: ::Array[Increase::Models::ExportCreateParams::EntityCsv::Status::in_]

          def initialize: (
            in_: ::Array[Increase::Models::ExportCreateParams::EntityCsv::Status::in_]
          ) -> void

          def to_hash: -> {
            in_: ::Array[Increase::Models::ExportCreateParams::EntityCsv::Status::in_]
          }

          type in_ = :active | :archived | :disabled

          module In
            extend Increase::Internal::Type::Enum

            # The entity is active.
            ACTIVE: :active

            # The entity is archived, and can no longer be used to create accounts.
            ARCHIVED: :archived

            # The entity is temporarily disabled and cannot be used for financial activity.
            DISABLED: :disabled

            def self?.values: -> ::Array[Increase::Models::ExportCreateParams::EntityCsv::Status::in_]
          end
        end
      end

      type transaction_csv =
        {
          account_id: String,
          created_at: Increase::ExportCreateParams::TransactionCsv::CreatedAt,
          program_id: String
        }

      class TransactionCsv < Increase::Internal::Type::BaseModel
        attr_reader account_id: String?

        def account_id=: (String) -> String

        attr_reader created_at: Increase::ExportCreateParams::TransactionCsv::CreatedAt?

        def created_at=: (
          Increase::ExportCreateParams::TransactionCsv::CreatedAt
        ) -> Increase::ExportCreateParams::TransactionCsv::CreatedAt

        attr_reader program_id: String?

        def program_id=: (String) -> String

        def initialize: (
          ?account_id: String,
          ?created_at: Increase::ExportCreateParams::TransactionCsv::CreatedAt,
          ?program_id: String
        ) -> void

        def to_hash: -> {
          account_id: String,
          created_at: Increase::ExportCreateParams::TransactionCsv::CreatedAt,
          program_id: String
        }

        type created_at =
          { after: Time, before: Time, on_or_after: Time, on_or_before: Time }

        class CreatedAt < Increase::Internal::Type::BaseModel
          attr_reader after: Time?

          def after=: (Time) -> Time

          attr_reader before: Time?

          def before=: (Time) -> Time

          attr_reader on_or_after: Time?

          def on_or_after=: (Time) -> Time

          attr_reader on_or_before: Time?

          def on_or_before=: (Time) -> Time

          def initialize: (
            ?after: Time,
            ?before: Time,
            ?on_or_after: Time,
            ?on_or_before: Time
          ) -> void

          def to_hash: -> {
            after: Time,
            before: Time,
            on_or_after: Time,
            on_or_before: Time
          }
        end
      end
    end
  end
end
