module Increase
  module Models
    type external_account_create_params =
      {
        account_number: String,
        description: String,
        routing_number: String,
        account_holder: Increase::Models::ExternalAccountCreateParams::account_holder,
        funding: Increase::Models::ExternalAccountCreateParams::funding
      }
      & Increase::Internal::Type::request_parameters

    class ExternalAccountCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor account_number: String

      attr_accessor description: String

      attr_accessor routing_number: String

      attr_reader account_holder: Increase::Models::ExternalAccountCreateParams::account_holder?

      def account_holder=: (
        Increase::Models::ExternalAccountCreateParams::account_holder
      ) -> Increase::Models::ExternalAccountCreateParams::account_holder

      attr_reader funding: Increase::Models::ExternalAccountCreateParams::funding?

      def funding=: (
        Increase::Models::ExternalAccountCreateParams::funding
      ) -> Increase::Models::ExternalAccountCreateParams::funding

      def initialize: (
        account_number: String,
        description: String,
        routing_number: String,
        ?account_holder: Increase::Models::ExternalAccountCreateParams::account_holder,
        ?funding: Increase::Models::ExternalAccountCreateParams::funding,
        ?request_options: Increase::request_opts
      ) -> void

      type account_holder = :business | :individual | :unknown

      module AccountHolder
        extend Increase::Internal::Type::Enum

        # The External Account is owned by a business.
        BUSINESS: :business

        # The External Account is owned by an individual.
        INDIVIDUAL: :individual

        # It's unknown what kind of entity owns the External Account.
        UNKNOWN: :unknown

        def self?.values: -> ::Array[Increase::Models::ExternalAccountCreateParams::account_holder]
      end

      type funding = :checking | :savings | :other

      module Funding
        extend Increase::Internal::Type::Enum

        # A checking account.
        CHECKING: :checking

        # A savings account.
        SAVINGS: :savings

        # A different type of account.
        OTHER: :other

        def self?.values: -> ::Array[Increase::Models::ExternalAccountCreateParams::funding]
      end
    end
  end
end
