module Increase
  module Models
    type file =
      {
        id: String,
        created_at: Time,
        description: String?,
        direction: Increase::Models::File::direction,
        filename: String?,
        idempotency_key: String?,
        mime_type: String,
        purpose: Increase::Models::File::purpose,
        type: Increase::Models::File::type_
      }

    class File < Increase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor description: String?

      attr_accessor direction: Increase::Models::File::direction

      attr_accessor filename: String?

      attr_accessor idempotency_key: String?

      attr_accessor mime_type: String

      attr_accessor purpose: Increase::Models::File::purpose

      attr_accessor type: Increase::Models::File::type_

      def initialize: (
        id: String,
        created_at: Time,
        description: String?,
        direction: Increase::Models::File::direction,
        filename: String?,
        idempotency_key: String?,
        mime_type: String,
        purpose: Increase::Models::File::purpose,
        type: Increase::Models::File::type_
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        description: String?,
        direction: Increase::Models::File::direction,
        filename: String?,
        idempotency_key: String?,
        mime_type: String,
        purpose: Increase::Models::File::purpose,
        type: Increase::Models::File::type_
      }

      type direction = :to_increase | :from_increase

      module Direction
        extend Increase::Internal::Type::Enum

        # This File was sent by you to Increase.
        TO_INCREASE: :to_increase

        # This File was generated by Increase.
        FROM_INCREASE: :from_increase

        def self?.values: -> ::Array[Increase::Models::File::direction]
      end

      type purpose =
        :check_image_front
        | :check_image_back
        | :processed_check_image_front
        | :processed_check_image_back
        | :mailed_check_image
        | :check_attachment
        | :inbound_mail_item
        | :form_1099_int
        | :form_1099_misc
        | :form_ss_4
        | :identity_document
        | :increase_statement
        | :other
        | :trust_formation_document
        | :digital_wallet_artwork
        | :digital_wallet_app_icon
        | :physical_card_front
        | :physical_card_back
        | :physical_card_carrier
        | :document_request
        | :entity_supplemental_document
        | :export
        | :unusual_activity_report_attachment
        | :deposit_account_control_agreement
        | :proof_of_authorization_request_submission
        | :account_verification_letter
        | :funding_instructions

      module Purpose
        extend Increase::Internal::Type::Enum

        # An image of the front of a check, used for check deposits.
        CHECK_IMAGE_FRONT: :check_image_front

        # An image of the back of a check, used for check deposits.
        CHECK_IMAGE_BACK: :check_image_back

        # An image of the front of a deposited check after processing by Increase and submission to the Federal Reserve.
        PROCESSED_CHECK_IMAGE_FRONT: :processed_check_image_front

        # An image of the back of a deposited check after processing by Increase and submission to the Federal Reserve.
        PROCESSED_CHECK_IMAGE_BACK: :processed_check_image_back

        # An image of a check that was mailed to a recipient.
        MAILED_CHECK_IMAGE: :mailed_check_image

        # A document to be printed on an additional page and mailed with a check that you've requested Increase print.
        CHECK_ATTACHMENT: :check_attachment

        # A scanned mail item sent to Increase.
        INBOUND_MAIL_ITEM: :inbound_mail_item

        # IRS Form 1099-INT.
        FORM_1099_INT: :form_1099_int

        # IRS Form 1099-MISC.
        FORM_1099_MISC: :form_1099_misc

        # IRS Form SS-4.
        FORM_SS_4: :form_ss_4

        # An image of a government-issued ID.
        IDENTITY_DOCUMENT: :identity_document

        # A statement generated by Increase.
        INCREASE_STATEMENT: :increase_statement

        # A file purpose not covered by any of the other cases.
        OTHER: :other

        # A legal document forming a trust.
        TRUST_FORMATION_DOCUMENT: :trust_formation_document

        # A card image to be rendered inside digital wallet apps. This must be a 1536x969 pixel PNG.
        DIGITAL_WALLET_ARTWORK: :digital_wallet_artwork

        # An icon for you app to be rendered inside digital wallet apps. This must be a 100x100 pixel PNG.
        DIGITAL_WALLET_APP_ICON: :digital_wallet_app_icon

        # A card image to be printed on the front of a physical card. This must be a 2100x1340 pixel PNG with no other color but black.
        PHYSICAL_CARD_FRONT: :physical_card_front

        # The image to be printed on the back of a physical card.
        PHYSICAL_CARD_BACK: :physical_card_back

        # An image representing the entirety of the carrier used for a physical card. This must be a 2550x3300 pixel PNG with no other color but black.
        PHYSICAL_CARD_CARRIER: :physical_card_carrier

        # A document requested by Increase.
        DOCUMENT_REQUEST: :document_request

        # A supplemental document associated an an Entity.
        ENTITY_SUPPLEMENTAL_DOCUMENT: :entity_supplemental_document

        # The results of an Export you requested via the dashboard or API.
        EXPORT: :export

        # An attachment to an Unusual Activity Report.
        UNUSUAL_ACTIVITY_REPORT_ATTACHMENT: :unusual_activity_report_attachment

        # A document granting another entity access to the funds into your account.
        DEPOSIT_ACCOUNT_CONTROL_AGREEMENT: :deposit_account_control_agreement

        # A file containing additional evidence for a Proof of Authorization Request Submission.
        PROOF_OF_AUTHORIZATION_REQUEST_SUBMISSION: :proof_of_authorization_request_submission

        # An account verification letter.
        ACCOUNT_VERIFICATION_LETTER: :account_verification_letter

        # Funding instructions.
        FUNDING_INSTRUCTIONS: :funding_instructions

        def self?.values: -> ::Array[Increase::Models::File::purpose]
      end

      type type_ = :file

      module Type
        extend Increase::Internal::Type::Enum

        FILE: :file

        def self?.values: -> ::Array[Increase::Models::File::type_]
      end
    end
  end
end
