module Increase
  module Models
    type file_link_create_params =
      { file_id: String, expires_at: Time }
      & Increase::Internal::Type::request_parameters

    class FileLinkCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor file_id: String

      attr_reader expires_at: Time?

      def expires_at=: (Time) -> Time

      def initialize: (
        file_id: String,
        ?expires_at: Time,
        ?request_options: Increase::request_opts
      ) -> void
    end
  end
end
