module Increase
  module Models
    type file_link =
      {
        id: String,
        created_at: Time,
        expires_at: Time,
        file_id: String,
        idempotency_key: String?,
        type: Increase::Models::FileLink::type_,
        unauthenticated_url: String
      }

    class FileLink < Increase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor expires_at: Time

      attr_accessor file_id: String

      attr_accessor idempotency_key: String?

      attr_accessor type: Increase::Models::FileLink::type_

      attr_accessor unauthenticated_url: String

      def initialize: (
        id: String,
        created_at: Time,
        expires_at: Time,
        file_id: String,
        idempotency_key: String?,
        type: Increase::Models::FileLink::type_,
        unauthenticated_url: String
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        expires_at: Time,
        file_id: String,
        idempotency_key: String?,
        type: Increase::Models::FileLink::type_,
        unauthenticated_url: String
      }

      type type_ = :file_link

      module Type
        extend Increase::Internal::Type::Enum

        FILE_LINK: :file_link

        def self?.values: -> ::Array[Increase::Models::FileLink::type_]
      end
    end
  end
end
