module Increase
  module Models
    type inbound_check_deposit_return_params =
      { reason: Increase::Models::InboundCheckDepositReturnParams::reason }
      & Increase::Internal::Type::request_parameters

    class InboundCheckDepositReturnParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor reason: Increase::Models::InboundCheckDepositReturnParams::reason

      def initialize: (
        reason: Increase::Models::InboundCheckDepositReturnParams::reason,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> Increase::Models::inbound_check_deposit_return_params

      type reason =
        :altered_or_fictitious
        | :not_authorized
        | :duplicate_presentment
        | :endorsement_missing
        | :endorsement_irregular

      module Reason
        extend Increase::Internal::Type::Enum

        # The check was altered or fictitious.
        ALTERED_OR_FICTITIOUS: :altered_or_fictitious

        # The check was not authorized.
        NOT_AUTHORIZED: :not_authorized

        # The check was a duplicate presentment.
        DUPLICATE_PRESENTMENT: :duplicate_presentment

        # The check was not endorsed.
        ENDORSEMENT_MISSING: :endorsement_missing

        # The check was not endorsed by the payee.
        ENDORSEMENT_IRREGULAR: :endorsement_irregular

        def self?.values: -> ::Array[Increase::Models::InboundCheckDepositReturnParams::reason]
      end
    end
  end
end
