module Increase
  module Models
    type inbound_ach_transfer_create_notification_of_change_params = ({updated_account_number: String, updated_routing_number: String} & Increase::request_parameters)

    class InboundACHTransferCreateNotificationOfChangeParams < Increase::BaseModel
      extend Increase::RequestParameters::Converter
      include Increase::RequestParameters

      attr_reader updated_account_number: String?

      def updated_account_number=: (String) -> String

      attr_reader updated_routing_number: String?

      def updated_routing_number=: (String) -> String

      def initialize: (updated_account_number: String, updated_routing_number: String, request_options: Increase::request_opts) -> void
                    | (?(Increase::Models::inbound_ach_transfer_create_notification_of_change_params | Increase::BaseModel) data) -> void

      def to_hash: () -> Increase::Models::inbound_ach_transfer_create_notification_of_change_params
    end
  end
end
