module Increase
  module Models
    type inbound_wire_drawdown_request_list_params =
      { cursor: String, limit: Integer }
      & Increase::Internal::Type::request_parameters

    class InboundWireDrawdownRequestListParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      def initialize: (
        ?cursor: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        cursor: String,
        limit: Integer,
        request_options: Increase::RequestOptions
      }
    end
  end
end
