module Increase
  module Models
    type inbound_ach_transfer_retrieve_params =
      {  } & Increase::request_parameters

    class InboundACHTransferRetrieveParams < Increase::BaseModel
      extend Increase::RequestParameters::Converter
      include Increase::RequestParameters

      def initialize: (?request_options: Increase::request_opts) -> void

      def to_hash: -> Increase::Models::inbound_ach_transfer_retrieve_params
    end
  end
end
