module Increase
  module Models
    type inbound_real_time_payments_transfer_retrieve_params =
      {  } & Increase::Internal::Type::request_parameters

    class InboundRealTimePaymentsTransferRetrieveParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      def initialize: (?request_options: Increase::request_opts) -> void

      def to_hash: -> Increase::Models::inbound_real_time_payments_transfer_retrieve_params
    end
  end
end
