module Increase
  module Models
    type inbound_wire_drawdown_request =
      {
        id: String,
        amount: Integer,
        beneficiary_account_number: String,
        :beneficiary_address_line1 => String?,
        :beneficiary_address_line2 => String?,
        :beneficiary_address_line3 => String?,
        beneficiary_name: String?,
        beneficiary_routing_number: String,
        created_at: Time,
        currency: String,
        message_to_recipient: String?,
        originator_account_number: String?,
        :originator_address_line1 => String?,
        :originator_address_line2 => String?,
        :originator_address_line3 => String?,
        originator_name: String?,
        originator_routing_number: String,
        :originator_to_beneficiary_information_line1 => String?,
        :originator_to_beneficiary_information_line2 => String?,
        :originator_to_beneficiary_information_line3 => String?,
        :originator_to_beneficiary_information_line4 => String?,
        recipient_account_number_id: String,
        type: Increase::InboundWireDrawdownRequest::type_
      }

    class InboundWireDrawdownRequest < Increase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor amount: Integer

      attr_accessor beneficiary_account_number: String

      attr_accessor beneficiary_address_line1: String?

      attr_accessor beneficiary_address_line2: String?

      attr_accessor beneficiary_address_line3: String?

      attr_accessor beneficiary_name: String?

      attr_accessor beneficiary_routing_number: String

      attr_accessor created_at: Time

      attr_accessor currency: String

      attr_accessor message_to_recipient: String?

      attr_accessor originator_account_number: String?

      attr_accessor originator_address_line1: String?

      attr_accessor originator_address_line2: String?

      attr_accessor originator_address_line3: String?

      attr_accessor originator_name: String?

      attr_accessor originator_routing_number: String

      attr_accessor originator_to_beneficiary_information_line1: String?

      attr_accessor originator_to_beneficiary_information_line2: String?

      attr_accessor originator_to_beneficiary_information_line3: String?

      attr_accessor originator_to_beneficiary_information_line4: String?

      attr_accessor recipient_account_number_id: String

      attr_accessor type: Increase::InboundWireDrawdownRequest::type_

      def initialize: (
        id: String,
        amount: Integer,
        beneficiary_account_number: String,
        beneficiary_address_line1: String?,
        beneficiary_address_line2: String?,
        beneficiary_address_line3: String?,
        beneficiary_name: String?,
        beneficiary_routing_number: String,
        created_at: Time,
        currency: String,
        message_to_recipient: String?,
        originator_account_number: String?,
        originator_address_line1: String?,
        originator_address_line2: String?,
        originator_address_line3: String?,
        originator_name: String?,
        originator_routing_number: String,
        originator_to_beneficiary_information_line1: String?,
        originator_to_beneficiary_information_line2: String?,
        originator_to_beneficiary_information_line3: String?,
        originator_to_beneficiary_information_line4: String?,
        recipient_account_number_id: String,
        type: Increase::InboundWireDrawdownRequest::type_
      ) -> void

      type type_ = :inbound_wire_drawdown_request

      module Type
        extend Increase::Internal::Type::Enum

        INBOUND_WIRE_DRAWDOWN_REQUEST: :inbound_wire_drawdown_request

        def self?.values: -> ::Array[Increase::InboundWireDrawdownRequest::type_]
      end
    end
  end
end
