module Increase
  module Models
    type inbound_wire_drawdown_request_list_params = ({cursor: String, limit: Integer} & Increase::request_parameters)

    class InboundWireDrawdownRequestListParams < Increase::BaseModel
      extend Increase::RequestParameters::Converter
      include Increase::RequestParameters

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      def initialize: (cursor: String, limit: Integer, request_options: Increase::request_opts) -> void
                    | (?(Increase::Models::inbound_wire_drawdown_request_list_params | Increase::BaseModel) data) -> void

      def to_hash: () -> Increase::Models::inbound_wire_drawdown_request_list_params
    end
  end
end
