module Increase
  module Models
    type intrafi_exclusion_archive_params = {  } & Increase::request_parameters

    class IntrafiExclusionArchiveParams < Increase::BaseModel
      extend Increase::Type::RequestParameters::Converter
      include Increase::RequestParameters

      def initialize: (?request_options: Increase::request_opts) -> void

      def to_hash: -> Increase::Models::intrafi_exclusion_archive_params
    end
  end
end
