module Increase
  module Models
    type intrafi_account_enrollment_create_params =
      { account_id: String, email_address: String }
      & Increase::Internal::Type::request_parameters

    class IntrafiAccountEnrollmentCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor account_id: String

      attr_accessor email_address: String

      def initialize: (
        account_id: String,
        email_address: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> Increase::Models::intrafi_account_enrollment_create_params
    end
  end
end
