module Increase
  module Models
    type intrafi_exclusion =
      {
        id: String,
        bank_name: String,
        created_at: Time,
        entity_id: String,
        excluded_at: Time?,
        fdic_certificate_number: String?,
        idempotency_key: String?,
        status: Increase::IntrafiExclusion::status,
        submitted_at: Time?,
        type: Increase::IntrafiExclusion::type_
      }

    class IntrafiExclusion < Increase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor bank_name: String

      attr_accessor created_at: Time

      attr_accessor entity_id: String

      attr_accessor excluded_at: Time?

      attr_accessor fdic_certificate_number: String?

      attr_accessor idempotency_key: String?

      attr_accessor status: Increase::IntrafiExclusion::status

      attr_accessor submitted_at: Time?

      attr_accessor type: Increase::IntrafiExclusion::type_

      def initialize: (
        id: String,
        bank_name: String,
        created_at: Time,
        entity_id: String,
        excluded_at: Time?,
        fdic_certificate_number: String?,
        idempotency_key: String?,
        status: Increase::IntrafiExclusion::status,
        submitted_at: Time?,
        type: Increase::IntrafiExclusion::type_
      ) -> void

      type status = :pending | :completed | :archived

      module Status
        extend Increase::Internal::Type::Enum

        # The exclusion is being added to the IntraFi network.
        PENDING: :pending

        # The exclusion has been added to the IntraFi network.
        COMPLETED: :completed

        # The exclusion has been removed from the IntraFi network.
        ARCHIVED: :archived

        def self?.values: -> ::Array[Increase::IntrafiExclusion::status]
      end

      type type_ = :intrafi_exclusion

      module Type
        extend Increase::Internal::Type::Enum

        INTRAFI_EXCLUSION: :intrafi_exclusion

        def self?.values: -> ::Array[Increase::IntrafiExclusion::type_]
      end
    end
  end
end
