module Increase
  module Models
    type intrafi_account_enrollment_list_params =
      {
        account_id: String,
        cursor: String,
        idempotency_key: String,
        limit: Integer,
        status: Increase::Models::IntrafiAccountEnrollmentListParams::Status
      }
      & Increase::Internal::Type::request_parameters

    class IntrafiAccountEnrollmentListParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader status: Increase::Models::IntrafiAccountEnrollmentListParams::Status?

      def status=: (
        Increase::Models::IntrafiAccountEnrollmentListParams::Status
      ) -> Increase::Models::IntrafiAccountEnrollmentListParams::Status

      def initialize: (
        ?account_id: String,
        ?cursor: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?status: Increase::Models::IntrafiAccountEnrollmentListParams::Status,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> Increase::Models::intrafi_account_enrollment_list_params

      type status =
        {
          in_: ::Array[Increase::Models::IntrafiAccountEnrollmentListParams::Status::in_]
        }

      class Status < Increase::Internal::Type::BaseModel
        attr_reader in_: ::Array[Increase::Models::IntrafiAccountEnrollmentListParams::Status::in_]?

        def in_=: (
          ::Array[Increase::Models::IntrafiAccountEnrollmentListParams::Status::in_]
        ) -> ::Array[Increase::Models::IntrafiAccountEnrollmentListParams::Status::in_]

        def initialize: (
          ?in_: ::Array[Increase::Models::IntrafiAccountEnrollmentListParams::Status::in_]
        ) -> void

        def to_hash: -> Increase::Models::IntrafiAccountEnrollmentListParams::status

        type in_ =
          :pending_enrolling
          | :enrolled
          | :pending_unenrolling
          | :unenrolled
          | :requires_attention

        module In
          extend Increase::Internal::Type::Enum

          # The account is being added to the IntraFi network.
          PENDING_ENROLLING: :pending_enrolling

          # The account has been enrolled with IntraFi.
          ENROLLED: :enrolled

          # The account is being unenrolled from IntraFi's deposit sweep.
          PENDING_UNENROLLING: :pending_unenrolling

          # The account was once enrolled, but is no longer enrolled at IntraFi.
          UNENROLLED: :unenrolled

          # Something unexpected happened with this account. Contact Increase support.
          REQUIRES_ATTENTION: :requires_attention

          def self?.values: -> ::Array[Increase::Models::IntrafiAccountEnrollmentListParams::Status::in_]
        end
      end
    end
  end
end
