module Increase
  module Models
    type intrafi_balance_intrafi_balance_params =
      {  } & Increase::Internal::Type::request_parameters

    class IntrafiBalanceIntrafiBalanceParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      def initialize: (?request_options: Increase::request_opts) -> void

      def to_hash: -> Increase::Models::intrafi_balance_intrafi_balance_params
    end
  end
end
