module Increase
  module Models
    type intrafi_exclusion_archive_params =
      {  } & Increase::Internal::Type::request_parameters

    class IntrafiExclusionArchiveParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      def initialize: (?request_options: Increase::request_opts) -> void

      def to_hash: -> Increase::Models::intrafi_exclusion_archive_params
    end
  end
end
