module Increase
  module Models
    type lockbox_create_params =
      { account_id: String, description: String, recipient_name: String }
      & Increase::Internal::Type::request_parameters

    class LockboxCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor account_id: String

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader recipient_name: String?

      def recipient_name=: (String) -> String

      def initialize: (
        account_id: String,
        ?description: String,
        ?recipient_name: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> Increase::Models::lockbox_create_params
    end
  end
end
