module Increase
  module Models
    type oauth_application_retrieve_params = {  } & Increase::request_parameters

    class OAuthApplicationRetrieveParams < Increase::BaseModel
      extend Increase::RequestParameters::Converter
      include Increase::RequestParameters

      def initialize:
        (?request_options: Increase::request_opts) -> void
        | (
          ?Increase::Models::oauth_application_retrieve_params
          | Increase::BaseModel data
        ) -> void

      def to_hash: -> Increase::Models::oauth_application_retrieve_params
    end
  end
end
