module Increase
  module Models
    type pending_transaction_create_params =
      { account_id: String, amount: Integer, description: String }
      & Increase::Internal::Type::request_parameters

    class PendingTransactionCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor account_id: String

      attr_accessor amount: Integer

      attr_reader description: String?

      def description=: (String) -> String

      def initialize: (
        account_id: String,
        amount: Integer,
        ?description: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        amount: Integer,
        description: String,
        request_options: Increase::RequestOptions
      }
    end
  end
end
