module Increase
  module Models
    type physical_card_update_params =
      { status: Increase::Models::PhysicalCardUpdateParams::status }
      & Increase::Internal::Type::request_parameters

    class PhysicalCardUpdateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor status: Increase::Models::PhysicalCardUpdateParams::status

      def initialize: (
        status: Increase::Models::PhysicalCardUpdateParams::status,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        status: Increase::Models::PhysicalCardUpdateParams::status,
        request_options: Increase::RequestOptions
      }

      type status = :active | :disabled | :canceled

      module Status
        extend Increase::Internal::Type::Enum

        # The physical card is active.
        ACTIVE: :active

        # The physical card is temporarily disabled.
        DISABLED: :disabled

        # The physical card is permanently canceled.
        CANCELED: :canceled

        def self?.values: -> ::Array[Increase::Models::PhysicalCardUpdateParams::status]
      end
    end
  end
end
