module Increase
  module Models
    type physical_card_profile_list_params =
      {
        cursor: String,
        idempotency_key: String,
        limit: Integer,
        status: Increase::Models::PhysicalCardProfileListParams::Status
      }
      & Increase::Internal::Type::request_parameters

    class PhysicalCardProfileListParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader status: Increase::Models::PhysicalCardProfileListParams::Status?

      def status=: (
        Increase::Models::PhysicalCardProfileListParams::Status
      ) -> Increase::Models::PhysicalCardProfileListParams::Status

      def initialize: (
        ?cursor: String,
        ?idempotency_key: String,
        ?limit: Integer,
        ?status: Increase::Models::PhysicalCardProfileListParams::Status,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> Increase::Models::physical_card_profile_list_params

      type status =
        {
          in_: ::Array[Increase::Models::PhysicalCardProfileListParams::Status::in_]
        }

      class Status < Increase::Internal::Type::BaseModel
        attr_reader in_: ::Array[Increase::Models::PhysicalCardProfileListParams::Status::in_]?

        def in_=: (
          ::Array[Increase::Models::PhysicalCardProfileListParams::Status::in_]
        ) -> ::Array[Increase::Models::PhysicalCardProfileListParams::Status::in_]

        def initialize: (
          ?in_: ::Array[Increase::Models::PhysicalCardProfileListParams::Status::in_]
        ) -> void

        def to_hash: -> Increase::Models::PhysicalCardProfileListParams::status

        type in_ =
          :pending_creating
          | :pending_reviewing
          | :rejected
          | :pending_submitting
          | :active
          | :archived

        module In
          extend Increase::Internal::Type::Enum

          # The Card Profile has not yet been processed by Increase.
          PENDING_CREATING: :pending_creating

          # The card profile is awaiting review by Increase.
          PENDING_REVIEWING: :pending_reviewing

          # There is an issue with the Physical Card Profile preventing it from use.
          REJECTED: :rejected

          # The card profile is awaiting submission to the fulfillment provider.
          PENDING_SUBMITTING: :pending_submitting

          # The Physical Card Profile has been submitted to the fulfillment provider and is ready to use.
          ACTIVE: :active

          # The Physical Card Profile has been archived.
          ARCHIVED: :archived

          def self?.values: -> ::Array[Increase::Models::PhysicalCardProfileListParams::Status::in_]
        end
      end
    end
  end
end
