module Increase
  module Models
    type physical_card_profile =
      {
        id: String,
        back_image_file_id: String?,
        carrier_image_file_id: String?,
        contact_phone: String?,
        created_at: Time,
        creator: Increase::PhysicalCardProfile::creator,
        description: String,
        front_image_file_id: String?,
        idempotency_key: String?,
        is_default: bool,
        program_id: String,
        status: Increase::PhysicalCardProfile::status,
        type: Increase::PhysicalCardProfile::type_
      }

    class PhysicalCardProfile < Increase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor back_image_file_id: String?

      attr_accessor carrier_image_file_id: String?

      attr_accessor contact_phone: String?

      attr_accessor created_at: Time

      attr_accessor creator: Increase::PhysicalCardProfile::creator

      attr_accessor description: String

      attr_accessor front_image_file_id: String?

      attr_accessor idempotency_key: String?

      attr_accessor is_default: bool

      attr_accessor program_id: String

      attr_accessor status: Increase::PhysicalCardProfile::status

      attr_accessor type: Increase::PhysicalCardProfile::type_

      def initialize: (
        id: String,
        back_image_file_id: String?,
        carrier_image_file_id: String?,
        contact_phone: String?,
        created_at: Time,
        creator: Increase::PhysicalCardProfile::creator,
        description: String,
        front_image_file_id: String?,
        idempotency_key: String?,
        is_default: bool,
        program_id: String,
        status: Increase::PhysicalCardProfile::status,
        type: Increase::PhysicalCardProfile::type_
      ) -> void

      type creator = :increase | :user

      module Creator
        extend Increase::Internal::Type::Enum

        # This Physical Card Profile was created by Increase.
        INCREASE: :increase

        # This Physical Card Profile was created by you.
        USER: :user

        def self?.values: -> ::Array[Increase::PhysicalCardProfile::creator]
      end

      type status =
        :pending_creating
        | :pending_reviewing
        | :rejected
        | :pending_submitting
        | :active
        | :archived

      module Status
        extend Increase::Internal::Type::Enum

        # The Card Profile has not yet been processed by Increase.
        PENDING_CREATING: :pending_creating

        # The card profile is awaiting review by Increase.
        PENDING_REVIEWING: :pending_reviewing

        # There is an issue with the Physical Card Profile preventing it from use.
        REJECTED: :rejected

        # The card profile is awaiting submission to the fulfillment provider.
        PENDING_SUBMITTING: :pending_submitting

        # The Physical Card Profile has been submitted to the fulfillment provider and is ready to use.
        ACTIVE: :active

        # The Physical Card Profile has been archived.
        ARCHIVED: :archived

        def self?.values: -> ::Array[Increase::PhysicalCardProfile::status]
      end

      type type_ = :physical_card_profile

      module Type
        extend Increase::Internal::Type::Enum

        PHYSICAL_CARD_PROFILE: :physical_card_profile

        def self?.values: -> ::Array[Increase::PhysicalCardProfile::type_]
      end
    end
  end
end
