module Increase
  module Models
    type physical_card_create_params =
      {
        card_id: String,
        cardholder: Increase::PhysicalCardCreateParams::Cardholder,
        shipment: Increase::PhysicalCardCreateParams::Shipment,
        physical_card_profile_id: String
      }
      & Increase::Internal::Type::request_parameters

    class PhysicalCardCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor card_id: String

      attr_accessor cardholder: Increase::PhysicalCardCreateParams::Cardholder

      attr_accessor shipment: Increase::PhysicalCardCreateParams::Shipment

      attr_reader physical_card_profile_id: String?

      def physical_card_profile_id=: (String) -> String

      def initialize: (
        card_id: String,
        cardholder: Increase::PhysicalCardCreateParams::Cardholder,
        shipment: Increase::PhysicalCardCreateParams::Shipment,
        ?physical_card_profile_id: String,
        ?request_options: Increase::request_opts
      ) -> void

      type cardholder = { first_name: String, last_name: String }

      class Cardholder < Increase::Internal::Type::BaseModel
        attr_accessor first_name: String

        attr_accessor last_name: String

        def initialize: (first_name: String, last_name: String) -> void
      end

      type shipment =
        {
          address: Increase::PhysicalCardCreateParams::Shipment::Address,
          method_: Increase::PhysicalCardCreateParams::Shipment::method_
        }

      class Shipment < Increase::Internal::Type::BaseModel
        attr_accessor address: Increase::PhysicalCardCreateParams::Shipment::Address

        attr_accessor method_: Increase::PhysicalCardCreateParams::Shipment::method_

        def initialize: (
          address: Increase::PhysicalCardCreateParams::Shipment::Address,
          method_: Increase::PhysicalCardCreateParams::Shipment::method_
        ) -> void

        type address =
          {
            city: String,
            :line1 => String,
            name: String,
            postal_code: String,
            state: String,
            :line2 => String,
            :line3 => String,
            phone_number: String
          }

        class Address < Increase::Internal::Type::BaseModel
          attr_accessor city: String

          attr_accessor line1: String

          attr_accessor name: String

          attr_accessor postal_code: String

          attr_accessor state: String

          attr_reader line2: String?

          def line2=: (String) -> String

          attr_reader line3: String?

          def line3=: (String) -> String

          attr_reader phone_number: String?

          def phone_number=: (String) -> String

          def initialize: (
            city: String,
            line1: String,
            name: String,
            postal_code: String,
            state: String,
            ?line2: String,
            ?line3: String,
            ?phone_number: String
          ) -> void
        end

        type method_ = :usps | :fedex_priority_overnight | :fedex_2_day

        module Method
          extend Increase::Internal::Type::Enum

          # USPS Post with tracking.
          USPS: :usps

          # FedEx Priority Overnight, no signature.
          FEDEX_PRIORITY_OVERNIGHT: :fedex_priority_overnight

          # FedEx 2-day.
          FEDEX_2_DAY: :fedex_2_day

          def self?.values: -> ::Array[Increase::PhysicalCardCreateParams::Shipment::method_]
        end
      end
    end
  end
end
