module Increase
  module Models
    type physical_card_profile_create_params =
      {
        carrier_image_file_id: String,
        contact_phone: String,
        description: String,
        front_image_file_id: String,
        program_id: String
      }
      & Increase::Internal::Type::request_parameters

    class PhysicalCardProfileCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor carrier_image_file_id: String

      attr_accessor contact_phone: String

      attr_accessor description: String

      attr_accessor front_image_file_id: String

      attr_accessor program_id: String

      def initialize: (
        carrier_image_file_id: String,
        contact_phone: String,
        description: String,
        front_image_file_id: String,
        program_id: String,
        ?request_options: Increase::request_opts
      ) -> void
    end
  end
end
