module Increase
  module Models
    type program_retrieve_params = ({} & Increase::request_parameters)

    class ProgramRetrieveParams < Increase::BaseModel
      extend Increase::RequestParameters::Converter
      include Increase::RequestParameters

      def initialize: (request_options: Increase::request_opts) -> void
                    | (?(Increase::Models::program_retrieve_params | Increase::BaseModel) data) -> void

      def to_hash: () -> Increase::Models::program_retrieve_params
    end
  end
end
