module Increase
  module Models
    type proof_of_authorization_request_submission_retrieve_params =
      {  } & Increase::Internal::Type::request_parameters

    class ProofOfAuthorizationRequestSubmissionRetrieveParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      def initialize: (?request_options: Increase::request_opts) -> void

      def to_hash: -> Increase::Models::proof_of_authorization_request_submission_retrieve_params
    end
  end
end
