module Increase
  module Models
    type proof_of_authorization_request_submission_create_params =
      {
        authorization_terms: String,
        authorized_at: Time,
        authorizer_email: String,
        authorizer_name: String,
        customer_has_been_offboarded: bool,
        proof_of_authorization_request_id: String,
        validated_account_ownership_via_credential: bool,
        validated_account_ownership_with_account_statement: bool,
        validated_account_ownership_with_microdeposit: bool,
        additional_evidence_file_id: String,
        authorizer_company: String,
        authorizer_ip_address: String
      }
      & Increase::Internal::Type::request_parameters

    class ProofOfAuthorizationRequestSubmissionCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor authorization_terms: String

      attr_accessor authorized_at: Time

      attr_accessor authorizer_email: String

      attr_accessor authorizer_name: String

      attr_accessor customer_has_been_offboarded: bool

      attr_accessor proof_of_authorization_request_id: String

      attr_accessor validated_account_ownership_via_credential: bool

      attr_accessor validated_account_ownership_with_account_statement: bool

      attr_accessor validated_account_ownership_with_microdeposit: bool

      attr_reader additional_evidence_file_id: String?

      def additional_evidence_file_id=: (String) -> String

      attr_reader authorizer_company: String?

      def authorizer_company=: (String) -> String

      attr_reader authorizer_ip_address: String?

      def authorizer_ip_address=: (String) -> String

      def initialize: (
        authorization_terms: String,
        authorized_at: Time,
        authorizer_email: String,
        authorizer_name: String,
        customer_has_been_offboarded: bool,
        proof_of_authorization_request_id: String,
        validated_account_ownership_via_credential: bool,
        validated_account_ownership_with_account_statement: bool,
        validated_account_ownership_with_microdeposit: bool,
        ?additional_evidence_file_id: String,
        ?authorizer_company: String,
        ?authorizer_ip_address: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> Increase::Models::proof_of_authorization_request_submission_create_params
    end
  end
end
