module Increase
  module Models
    type real_time_payments_transfer_retrieve_params =
      {  } & Increase::request_parameters

    class RealTimePaymentsTransferRetrieveParams < Increase::BaseModel
      extend Increase::Type::RequestParameters::Converter
      include Increase::RequestParameters

      def initialize: (?request_options: Increase::request_opts) -> void

      def to_hash: -> Increase::Models::real_time_payments_transfer_retrieve_params
    end
  end
end
