module Increase
  module Models
    type real_time_decision_retrieve_params =
      {  } & Increase::request_parameters

    class RealTimeDecisionRetrieveParams < Increase::BaseModel
      extend Increase::RequestParameters::Converter
      include Increase::RequestParameters

      def initialize:
        (?request_options: Increase::request_opts) -> void
        | (
          ?Increase::Models::real_time_decision_retrieve_params
          | Increase::BaseModel data
        ) -> void

      def to_hash: -> Increase::Models::real_time_decision_retrieve_params
    end
  end
end
