module Increase
  module Models
    type routing_number_list_response =
      {
        ach_transfers: Increase::Models::RoutingNumberListResponse::ach_transfers,
        name: String,
        real_time_payments_transfers: Increase::Models::RoutingNumberListResponse::real_time_payments_transfers,
        routing_number: String,
        type: Increase::Models::RoutingNumberListResponse::type_,
        wire_transfers: Increase::Models::RoutingNumberListResponse::wire_transfers
      }

    class RoutingNumberListResponse < Increase::Internal::Type::BaseModel
      attr_accessor ach_transfers: Increase::Models::RoutingNumberListResponse::ach_transfers

      attr_accessor name: String

      attr_accessor real_time_payments_transfers: Increase::Models::RoutingNumberListResponse::real_time_payments_transfers

      attr_accessor routing_number: String

      attr_accessor type: Increase::Models::RoutingNumberListResponse::type_

      attr_accessor wire_transfers: Increase::Models::RoutingNumberListResponse::wire_transfers

      def initialize: (
        ach_transfers: Increase::Models::RoutingNumberListResponse::ach_transfers,
        name: String,
        real_time_payments_transfers: Increase::Models::RoutingNumberListResponse::real_time_payments_transfers,
        routing_number: String,
        type: Increase::Models::RoutingNumberListResponse::type_,
        wire_transfers: Increase::Models::RoutingNumberListResponse::wire_transfers
      ) -> void

      def to_hash: -> Increase::Models::routing_number_list_response

      type ach_transfers = :supported | :not_supported

      module ACHTransfers
        extend Increase::Internal::Type::Enum

        # The routing number can receive this transfer type.
        SUPPORTED: :supported

        # The routing number cannot receive this transfer type.
        NOT_SUPPORTED: :not_supported

        def self?.values: -> ::Array[Increase::Models::RoutingNumberListResponse::ach_transfers]
      end

      type real_time_payments_transfers = :supported | :not_supported

      module RealTimePaymentsTransfers
        extend Increase::Internal::Type::Enum

        # The routing number can receive this transfer type.
        SUPPORTED: :supported

        # The routing number cannot receive this transfer type.
        NOT_SUPPORTED: :not_supported

        def self?.values: -> ::Array[Increase::Models::RoutingNumberListResponse::real_time_payments_transfers]
      end

      type type_ = :routing_number

      module Type
        extend Increase::Internal::Type::Enum

        ROUTING_NUMBER: :routing_number

        def self?.values: -> ::Array[Increase::Models::RoutingNumberListResponse::type_]
      end

      type wire_transfers = :supported | :not_supported

      module WireTransfers
        extend Increase::Internal::Type::Enum

        # The routing number can receive this transfer type.
        SUPPORTED: :supported

        # The routing number cannot receive this transfer type.
        NOT_SUPPORTED: :not_supported

        def self?.values: -> ::Array[Increase::Models::RoutingNumberListResponse::wire_transfers]
      end
    end
  end
end
