module Increase
  module Models
    type routing_number_list_params =
      { routing_number: String, cursor: String, limit: Integer }
      & Increase::Internal::Type::request_parameters

    class RoutingNumberListParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor routing_number: String

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      def initialize: (
        routing_number: String,
        ?cursor: String,
        ?limit: Integer,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        routing_number: String,
        cursor: String,
        limit: Integer,
        request_options: Increase::RequestOptions
      }
    end
  end
end
