module Increase
  module Models
    type supplemental_document_create_params =
      { entity_id: String, file_id: String }
      & Increase::Internal::Type::request_parameters

    class SupplementalDocumentCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor entity_id: String

      attr_accessor file_id: String

      def initialize: (
        entity_id: String,
        file_id: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> {
        entity_id: String,
        file_id: String,
        request_options: Increase::RequestOptions
      }
    end
  end
end
