module Increase
  module Models
    type wire_transfer_approve_params = {  } & Increase::request_parameters

    class WireTransferApproveParams < Increase::BaseModel
      extend Increase::Type::RequestParameters::Converter
      include Increase::RequestParameters

      def initialize: (?request_options: Increase::request_opts) -> void

      def to_hash: -> Increase::Models::wire_transfer_approve_params
    end
  end
end
