module Increase
  module Models
    type wire_transfer_create_params =
      {
        account_id: String,
        amount: Integer,
        beneficiary_name: String,
        message_to_recipient: String,
        account_number: String,
        :beneficiary_address_line1 => String,
        :beneficiary_address_line2 => String,
        :beneficiary_address_line3 => String,
        external_account_id: String,
        :originator_address_line1 => String,
        :originator_address_line2 => String,
        :originator_address_line3 => String,
        originator_name: String,
        require_approval: bool,
        routing_number: String,
        source_account_number_id: String
      }
      & Increase::Internal::Type::request_parameters

    class WireTransferCreateParams < Increase::Internal::Type::BaseModel
      extend Increase::Internal::Type::RequestParameters::Converter
      include Increase::Internal::Type::RequestParameters

      attr_accessor account_id: String

      attr_accessor amount: Integer

      attr_accessor beneficiary_name: String

      attr_accessor message_to_recipient: String

      attr_reader account_number: String?

      def account_number=: (String) -> String

      attr_reader beneficiary_address_line1: String?

      def beneficiary_address_line1=: (String) -> String

      attr_reader beneficiary_address_line2: String?

      def beneficiary_address_line2=: (String) -> String

      attr_reader beneficiary_address_line3: String?

      def beneficiary_address_line3=: (String) -> String

      attr_reader external_account_id: String?

      def external_account_id=: (String) -> String

      attr_reader originator_address_line1: String?

      def originator_address_line1=: (String) -> String

      attr_reader originator_address_line2: String?

      def originator_address_line2=: (String) -> String

      attr_reader originator_address_line3: String?

      def originator_address_line3=: (String) -> String

      attr_reader originator_name: String?

      def originator_name=: (String) -> String

      attr_reader require_approval: bool?

      def require_approval=: (bool) -> bool

      attr_reader routing_number: String?

      def routing_number=: (String) -> String

      attr_reader source_account_number_id: String?

      def source_account_number_id=: (String) -> String

      def initialize: (
        account_id: String,
        amount: Integer,
        beneficiary_name: String,
        message_to_recipient: String,
        ?account_number: String,
        ?beneficiary_address_line1: String,
        ?beneficiary_address_line2: String,
        ?beneficiary_address_line3: String,
        ?external_account_id: String,
        ?originator_address_line1: String,
        ?originator_address_line2: String,
        ?originator_address_line3: String,
        ?originator_name: String,
        ?require_approval: bool,
        ?routing_number: String,
        ?source_account_number_id: String,
        ?request_options: Increase::request_opts
      ) -> void

      def to_hash: -> Increase::Models::wire_transfer_create_params
    end
  end
end
