module Increase
  class Unknown = Increase::Internal::Type::Unknown

  class BooleanModel = Increase::Internal::Type::BooleanModel

  module Enum = Increase::Internal::Type::Enum

  module Union = Increase::Internal::Type::Union

  class ArrayOf = Increase::Internal::Type::ArrayOf

  class HashOf = Increase::Internal::Type::HashOf

  class BaseModel = Increase::Internal::Type::BaseModel

  type request_parameters = Increase::Internal::Type::request_parameters

  module RequestParameters = Increase::Internal::Type::RequestParameters
end
