module Increase
  module BasePage[Elem]
    def next_page?: -> bool

    def next_page: -> self

    def auto_paging_each: { (Elem arg0) -> void } -> void

    def to_enum: -> Enumerable[Elem]

    alias enum_for to_enum

    def initialize: (
      client: Increase::BaseClient,
      req: Increase::BaseClient::request,
      headers: ::Hash[String, String],
      unwrapped: top
    ) -> void
  end
end
