module Increase
  class Client < Increase::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    ENVIRONMENTS: {
      production: "https://api.increase.com",
      sandbox: "https://sandbox.increase.com"
    }

    attr_reader api_key: String

    attr_reader accounts: Increase::Resources::Accounts

    attr_reader account_numbers: Increase::Resources::AccountNumbers

    attr_reader cards: Increase::Resources::Cards

    attr_reader card_payments: Increase::Resources::CardPayments

    attr_reader card_purchase_supplements: Increase::Resources::CardPurchaseSupplements

    attr_reader card_disputes: Increase::Resources::CardDisputes

    attr_reader physical_cards: Increase::Resources::PhysicalCards

    attr_reader digital_card_profiles: Increase::Resources::DigitalCardProfiles

    attr_reader physical_card_profiles: Increase::Resources::PhysicalCardProfiles

    attr_reader digital_wallet_tokens: Increase::Resources::DigitalWalletTokens

    attr_reader transactions: Increase::Resources::Transactions

    attr_reader pending_transactions: Increase::Resources::PendingTransactions

    attr_reader declined_transactions: Increase::Resources::DeclinedTransactions

    attr_reader account_transfers: Increase::Resources::AccountTransfers

    attr_reader ach_transfers: Increase::Resources::ACHTransfers

    attr_reader ach_prenotifications: Increase::Resources::ACHPrenotifications

    attr_reader inbound_ach_transfers: Increase::Resources::InboundACHTransfers

    attr_reader wire_transfers: Increase::Resources::WireTransfers

    attr_reader inbound_wire_transfers: Increase::Resources::InboundWireTransfers

    attr_reader wire_drawdown_requests: Increase::Resources::WireDrawdownRequests

    attr_reader inbound_wire_drawdown_requests: Increase::Resources::InboundWireDrawdownRequests

    attr_reader check_transfers: Increase::Resources::CheckTransfers

    attr_reader inbound_check_deposits: Increase::Resources::InboundCheckDeposits

    attr_reader real_time_payments_transfers: Increase::Resources::RealTimePaymentsTransfers

    attr_reader inbound_real_time_payments_transfers: Increase::Resources::InboundRealTimePaymentsTransfers

    attr_reader check_deposits: Increase::Resources::CheckDeposits

    attr_reader lockboxes: Increase::Resources::Lockboxes

    attr_reader inbound_mail_items: Increase::Resources::InboundMailItems

    attr_reader routing_numbers: Increase::Resources::RoutingNumbers

    attr_reader external_accounts: Increase::Resources::ExternalAccounts

    attr_reader entities: Increase::Resources::Entities

    attr_reader supplemental_documents: Increase::Resources::SupplementalDocuments

    attr_reader programs: Increase::Resources::Programs

    attr_reader proof_of_authorization_requests: Increase::Resources::ProofOfAuthorizationRequests

    attr_reader proof_of_authorization_request_submissions: Increase::Resources::ProofOfAuthorizationRequestSubmissions

    attr_reader account_statements: Increase::Resources::AccountStatements

    attr_reader files: Increase::Resources::Files

    attr_reader documents: Increase::Resources::Documents

    attr_reader exports: Increase::Resources::Exports

    attr_reader events: Increase::Resources::Events

    attr_reader event_subscriptions: Increase::Resources::EventSubscriptions

    attr_reader real_time_decisions: Increase::Resources::RealTimeDecisions

    attr_reader bookkeeping_accounts: Increase::Resources::BookkeepingAccounts

    attr_reader bookkeeping_entry_sets: Increase::Resources::BookkeepingEntrySets

    attr_reader bookkeeping_entries: Increase::Resources::BookkeepingEntries

    attr_reader groups: Increase::Resources::Groups

    attr_reader oauth_applications: Increase::Resources::OAuthApplications

    attr_reader oauth_connections: Increase::Resources::OAuthConnections

    attr_reader oauth_tokens: Increase::Resources::OAuthTokens

    attr_reader intrafi_account_enrollments: Increase::Resources::IntrafiAccountEnrollments

    attr_reader intrafi_balances: Increase::Resources::IntrafiBalances

    attr_reader intrafi_exclusions: Increase::Resources::IntrafiExclusions

    attr_reader simulations: Increase::Resources::Simulations

    private def auth_headers: -> ::Hash[String, String]

    def initialize: (
      environment: :production | :sandbox | nil,
      base_url: String?,
      api_key: String?,
      max_retries: Integer,
      timeout: Float,
      initial_retry_delay: Float,
      max_retry_delay: Float,
      idempotency_header: String
    ) -> void
  end
end
