module Increase
  class Error < StandardError
    attr_reader cause: StandardError?
  end

  class ConversionError < Increase::Error
  end

  class APIError < Increase::Error
    attr_reader url: URI::Generic

    attr_reader status: Integer?

    attr_reader body: top?

    def initialize: (url: URI::Generic, status: Integer?, body: Object?, request: nil, response: nil, message: String?) -> void
  end

  class APIConnectionError < Increase::APIError
    def initialize: (url: URI::Generic, status: nil, body: nil, request: nil, response: nil, message: String?) -> void
  end

  class APITimeoutError < Increase::APIConnectionError
    def initialize: (url: URI::Generic, status: nil, body: nil, request: nil, response: nil, message: String?) -> void
  end

  class APIStatusError < Increase::APIError
    def self.for: (url: URI::Generic, status: Integer, body: Object?, request: nil, response: nil) -> instance

    def initialize: (url: URI::Generic, status: Integer, body: Object?, request: nil, response: nil, message: String?) -> void
  end

  class BadRequestError < Increase::APIStatusError
    HTTP_STATUS: 400
  end

  class AuthenticationError < Increase::APIStatusError
    HTTP_STATUS: 401
  end

  class PermissionDeniedError < Increase::APIStatusError
    HTTP_STATUS: 403
  end

  class NotFoundError < Increase::APIStatusError
    HTTP_STATUS: 404
  end

  class ConflictError < Increase::APIStatusError
    HTTP_STATUS: 409
  end

  class UnprocessableEntityError < Increase::APIStatusError
    HTTP_STATUS: 422
  end

  class RateLimitError < Increase::APIStatusError
    HTTP_STATUS: 429
  end

  class InvalidParametersError < Increase::BadRequestError
    HTTP_STATUS: 400

    TYPE: "invalid_parameters_error"
  end

  class MalformedRequestError < Increase::BadRequestError
    HTTP_STATUS: 400

    TYPE: "malformed_request_error"
  end

  class InvalidAPIKeyError < Increase::AuthenticationError
    HTTP_STATUS: 401

    TYPE: "invalid_api_key_error"
  end

  class EnvironmentMismatchError < Increase::PermissionDeniedError
    HTTP_STATUS: 403

    TYPE: "environment_mismatch_error"
  end

  class InsufficientPermissionsError < Increase::PermissionDeniedError
    HTTP_STATUS: 403

    TYPE: "insufficient_permissions_error"
  end

  class PrivateFeatureError < Increase::PermissionDeniedError
    HTTP_STATUS: 403

    TYPE: "private_feature_error"
  end

  class APIMethodNotFoundError < Increase::NotFoundError
    HTTP_STATUS: 404

    TYPE: "api_method_not_found_error"
  end

  class ObjectNotFoundError < Increase::NotFoundError
    HTTP_STATUS: 404

    TYPE: "object_not_found_error"
  end

  class IdempotencyKeyAlreadyUsedError < Increase::ConflictError
    HTTP_STATUS: 409

    TYPE: "idempotency_key_already_used_error"
  end

  class InvalidOperationError < Increase::ConflictError
    HTTP_STATUS: 409

    TYPE: "invalid_operation_error"
  end

  class RateLimitedError < Increase::RateLimitError
    HTTP_STATUS: 429

    TYPE: "rate_limited_error"
  end

  class InternalServerError < Increase::APIStatusError
    HTTP_STATUS: Range[Integer]

    TYPE: "internal_server_error"
  end
end
