module Increase
  class Page[Elem]
    include Increase::BasePage[Elem]

    attr_accessor data: ::Array[Elem]

    attr_accessor next_cursor: String?

    def initialize: (client: Increase::BaseClient, req: Increase::BaseClient::request_components, headers: ::Hash[String, String], page_data: ::Hash[Symbol, top]) -> void
  end
end
