module Increase
  module Models
    module Simulations
      type ach_transfer_settle_params =
        {  } & Increase::Internal::Type::request_parameters

      class ACHTransferSettleParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        def initialize: (?request_options: Increase::request_opts) -> void

        def to_hash: -> { request_options: Increase::RequestOptions }
      end
    end
  end
end
