module Increase
  module Models
    module Simulations
      type ach_transfer_acknowledge_params = {  } & Increase::request_parameters

      class ACHTransferAcknowledgeParams < Increase::BaseModel
        extend Increase::Type::RequestParameters::Converter
        include Increase::RequestParameters

        def initialize: (?request_options: Increase::request_opts) -> void

        def to_hash: -> Increase::Models::Simulations::ach_transfer_acknowledge_params
      end
    end
  end
end
