module Increase
  module Models
    module Simulations
      type card_increment_create_params =
        {
          amount: Integer,
          card_payment_id: String,
          event_subscription_id: String
        }
        & Increase::Internal::Type::request_parameters

      class CardIncrementCreateParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor amount: Integer

        attr_accessor card_payment_id: String

        attr_reader event_subscription_id: String?

        def event_subscription_id=: (String) -> String

        def initialize: (
          amount: Integer,
          card_payment_id: String,
          ?event_subscription_id: String,
          ?request_options: Increase::request_opts
        ) -> void

        def to_hash: -> Increase::Models::Simulations::card_increment_create_params
      end
    end
  end
end
