module Increase
  module Models
    module Simulations
      type card_refund_create_params =
        { transaction_id: String }
        & Increase::Internal::Type::request_parameters

      class CardRefundCreateParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor transaction_id: String

        def initialize: (
          transaction_id: String,
          ?request_options: Increase::request_opts
        ) -> void

        def to_hash: -> {
          transaction_id: String,
          request_options: Increase::RequestOptions
        }
      end
    end
  end
end
