module Increase
  module Models
    module Simulations
      type card_settlement_create_params =
        { card_id: String, pending_transaction_id: String, amount: Integer }
        & Increase::Internal::Type::request_parameters

      class CardSettlementCreateParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor card_id: String

        attr_accessor pending_transaction_id: String

        attr_reader amount: Integer?

        def amount=: (Integer) -> Integer

        def initialize: (
          card_id: String,
          pending_transaction_id: String,
          ?amount: Integer,
          ?request_options: Increase::request_opts
        ) -> void
      end
    end
  end
end
