module Increase
  module Models
    module Simulations
      type card_fuel_confirmation_create_params =
        { amount: Integer, card_payment_id: String }
        & Increase::Internal::Type::request_parameters

      class CardFuelConfirmationCreateParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor amount: Integer

        attr_accessor card_payment_id: String

        def initialize: (
          amount: Integer,
          card_payment_id: String,
          ?request_options: Increase::request_opts
        ) -> void

        def to_hash: -> {
          amount: Integer,
          card_payment_id: String,
          request_options: Increase::RequestOptions
        }
      end
    end
  end
end
