module Increase
  module Models
    module Simulations
      type card_reversal_create_params =
        { card_payment_id: String, amount: Integer }
        & Increase::Internal::Type::request_parameters

      class CardReversalCreateParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor card_payment_id: String

        attr_reader amount: Integer?

        def amount=: (Integer) -> Integer

        def initialize: (
          card_payment_id: String,
          ?amount: Integer,
          ?request_options: Increase::request_opts
        ) -> void

        def to_hash: -> {
          card_payment_id: String,
          amount: Integer,
          request_options: Increase::RequestOptions
        }
      end
    end
  end
end
