module Increase
  module Models
    module Simulations
      type check_deposit_return_params = {  } & Increase::request_parameters

      class CheckDepositReturnParams < Increase::BaseModel
        extend Increase::RequestParameters::Converter
        include Increase::RequestParameters

        def initialize: (?request_options: Increase::request_opts) -> void

        def to_hash: -> Increase::Models::Simulations::check_deposit_return_params
      end
    end
  end
end
