module Increase
  module Models
    module Simulations
      type check_transfer_mail_params = {  } & Increase::request_parameters

      class CheckTransferMailParams < Increase::BaseModel
        extend Increase::RequestParameters::Converter
        include Increase::RequestParameters

        def initialize:
          (request_options: Increase::request_opts) -> void
          | (
            ?Increase::Models::Simulations::check_transfer_mail_params
            | Increase::BaseModel data
          ) -> void

        def to_hash: -> Increase::Models::Simulations::check_transfer_mail_params
      end
    end
  end
end
