module Increase
  module Models
    module Simulations
      type digital_wallet_token_request_create_params =
        { card_id: String } & Increase::Internal::Type::request_parameters

      class DigitalWalletTokenRequestCreateParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor card_id: String

        def initialize: (
          card_id: String,
          ?request_options: Increase::request_opts
        ) -> void
      end
    end
  end
end
