module Increase
  module Models
    module Simulations
      type digital_wallet_token_request_create_response =
        {
          decline_reason: Increase::Models::Simulations::DigitalWalletTokenRequestCreateResponse::decline_reason?,
          digital_wallet_token_id: String?,
          type: Increase::Models::Simulations::DigitalWalletTokenRequestCreateResponse::type_
        }

      class DigitalWalletTokenRequestCreateResponse < Increase::Internal::Type::BaseModel
        attr_accessor decline_reason: Increase::Models::Simulations::DigitalWalletTokenRequestCreateResponse::decline_reason?

        attr_accessor digital_wallet_token_id: String?

        attr_accessor type: Increase::Models::Simulations::DigitalWalletTokenRequestCreateResponse::type_

        def initialize: (
          decline_reason: Increase::Models::Simulations::DigitalWalletTokenRequestCreateResponse::decline_reason?,
          digital_wallet_token_id: String?,
          type: Increase::Models::Simulations::DigitalWalletTokenRequestCreateResponse::type_
        ) -> void

        def to_hash: -> {
          decline_reason: Increase::Models::Simulations::DigitalWalletTokenRequestCreateResponse::decline_reason?,
          digital_wallet_token_id: String?,
          type: Increase::Models::Simulations::DigitalWalletTokenRequestCreateResponse::type_
        }

        type decline_reason =
          :card_not_active
          | :no_verification_method
          | :webhook_timed_out
          | :webhook_declined

        module DeclineReason
          extend Increase::Internal::Type::Enum

          # The card is not active.
          CARD_NOT_ACTIVE: :card_not_active

          # The card does not have a two-factor authentication method.
          NO_VERIFICATION_METHOD: :no_verification_method

          # Your webhook timed out when evaluating the token provisioning attempt.
          WEBHOOK_TIMED_OUT: :webhook_timed_out

          # Your webhook declined the token provisioning attempt.
          WEBHOOK_DECLINED: :webhook_declined

          def self?.values: -> ::Array[Increase::Models::Simulations::DigitalWalletTokenRequestCreateResponse::decline_reason]
        end

        type type_ = :inbound_digital_wallet_token_request_simulation_result

        module Type
          extend Increase::Internal::Type::Enum

          INBOUND_DIGITAL_WALLET_TOKEN_REQUEST_SIMULATION_RESULT: :inbound_digital_wallet_token_request_simulation_result

          def self?.values: -> ::Array[Increase::Models::Simulations::DigitalWalletTokenRequestCreateResponse::type_]
        end
      end
    end
  end
end
