module Increase
  module Models
    module Simulations
      type inbound_real_time_payments_transfer_create_params =
        {
          account_number_id: String,
          amount: Integer,
          debtor_account_number: String,
          debtor_name: String,
          debtor_routing_number: String,
          remittance_information: String,
          request_for_payment_id: String
        }
        & Increase::Internal::Type::request_parameters

      class InboundRealTimePaymentsTransferCreateParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor account_number_id: String

        attr_accessor amount: Integer

        attr_reader debtor_account_number: String?

        def debtor_account_number=: (String) -> String

        attr_reader debtor_name: String?

        def debtor_name=: (String) -> String

        attr_reader debtor_routing_number: String?

        def debtor_routing_number=: (String) -> String

        attr_reader remittance_information: String?

        def remittance_information=: (String) -> String

        attr_reader request_for_payment_id: String?

        def request_for_payment_id=: (String) -> String

        def initialize: (
          account_number_id: String,
          amount: Integer,
          ?debtor_account_number: String,
          ?debtor_name: String,
          ?debtor_routing_number: String,
          ?remittance_information: String,
          ?request_for_payment_id: String,
          ?request_options: Increase::request_opts
        ) -> void

        def to_hash: -> Increase::Models::Simulations::inbound_real_time_payments_transfer_create_params
      end
    end
  end
end
