module Increase
  module Models
    module Simulations
      type inbound_wire_transfer_create_params =
        {
          account_number_id: String,
          amount: Integer,
          :beneficiary_address_line1 => String,
          :beneficiary_address_line2 => String,
          :beneficiary_address_line3 => String,
          beneficiary_name: String,
          beneficiary_reference: String,
          :originator_address_line1 => String,
          :originator_address_line2 => String,
          :originator_address_line3 => String,
          originator_name: String,
          originator_routing_number: String,
          :originator_to_beneficiary_information_line1 => String,
          :originator_to_beneficiary_information_line2 => String,
          :originator_to_beneficiary_information_line3 => String,
          :originator_to_beneficiary_information_line4 => String,
          sender_reference: String
        }
        & Increase::Internal::Type::request_parameters

      class InboundWireTransferCreateParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor account_number_id: String

        attr_accessor amount: Integer

        attr_reader beneficiary_address_line1: String?

        def beneficiary_address_line1=: (String) -> String

        attr_reader beneficiary_address_line2: String?

        def beneficiary_address_line2=: (String) -> String

        attr_reader beneficiary_address_line3: String?

        def beneficiary_address_line3=: (String) -> String

        attr_reader beneficiary_name: String?

        def beneficiary_name=: (String) -> String

        attr_reader beneficiary_reference: String?

        def beneficiary_reference=: (String) -> String

        attr_reader originator_address_line1: String?

        def originator_address_line1=: (String) -> String

        attr_reader originator_address_line2: String?

        def originator_address_line2=: (String) -> String

        attr_reader originator_address_line3: String?

        def originator_address_line3=: (String) -> String

        attr_reader originator_name: String?

        def originator_name=: (String) -> String

        attr_reader originator_routing_number: String?

        def originator_routing_number=: (String) -> String

        attr_reader originator_to_beneficiary_information_line1: String?

        def originator_to_beneficiary_information_line1=: (String) -> String

        attr_reader originator_to_beneficiary_information_line2: String?

        def originator_to_beneficiary_information_line2=: (String) -> String

        attr_reader originator_to_beneficiary_information_line3: String?

        def originator_to_beneficiary_information_line3=: (String) -> String

        attr_reader originator_to_beneficiary_information_line4: String?

        def originator_to_beneficiary_information_line4=: (String) -> String

        attr_reader sender_reference: String?

        def sender_reference=: (String) -> String

        def initialize: (
          account_number_id: String,
          amount: Integer,
          ?beneficiary_address_line1: String,
          ?beneficiary_address_line2: String,
          ?beneficiary_address_line3: String,
          ?beneficiary_name: String,
          ?beneficiary_reference: String,
          ?originator_address_line1: String,
          ?originator_address_line2: String,
          ?originator_address_line3: String,
          ?originator_name: String,
          ?originator_routing_number: String,
          ?originator_to_beneficiary_information_line1: String,
          ?originator_to_beneficiary_information_line2: String,
          ?originator_to_beneficiary_information_line3: String,
          ?originator_to_beneficiary_information_line4: String,
          ?sender_reference: String,
          ?request_options: Increase::request_opts
        ) -> void

        def to_hash: -> {
          account_number_id: String,
          amount: Integer,
          :beneficiary_address_line1 => String,
          :beneficiary_address_line2 => String,
          :beneficiary_address_line3 => String,
          beneficiary_name: String,
          beneficiary_reference: String,
          :originator_address_line1 => String,
          :originator_address_line2 => String,
          :originator_address_line3 => String,
          originator_name: String,
          originator_routing_number: String,
          :originator_to_beneficiary_information_line1 => String,
          :originator_to_beneficiary_information_line2 => String,
          :originator_to_beneficiary_information_line3 => String,
          :originator_to_beneficiary_information_line4 => String,
          sender_reference: String,
          request_options: Increase::RequestOptions
        }
      end
    end
  end
end
