module Increase
  module Models
    module Simulations
      type inbound_wire_drawdown_request_create_params =
        {
          amount: Integer,
          beneficiary_account_number: String,
          beneficiary_routing_number: String,
          currency: String,
          message_to_recipient: String,
          originator_account_number: String,
          originator_routing_number: String,
          recipient_account_number_id: String,
          :beneficiary_address_line1 => String,
          :beneficiary_address_line2 => String,
          :beneficiary_address_line3 => String,
          beneficiary_name: String,
          :originator_address_line1 => String,
          :originator_address_line2 => String,
          :originator_address_line3 => String,
          originator_name: String,
          :originator_to_beneficiary_information_line1 => String,
          :originator_to_beneficiary_information_line2 => String,
          :originator_to_beneficiary_information_line3 => String,
          :originator_to_beneficiary_information_line4 => String
        }
        & Increase::Internal::Type::request_parameters

      class InboundWireDrawdownRequestCreateParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor amount: Integer

        attr_accessor beneficiary_account_number: String

        attr_accessor beneficiary_routing_number: String

        attr_accessor currency: String

        attr_accessor message_to_recipient: String

        attr_accessor originator_account_number: String

        attr_accessor originator_routing_number: String

        attr_accessor recipient_account_number_id: String

        attr_reader beneficiary_address_line1: String?

        def beneficiary_address_line1=: (String) -> String

        attr_reader beneficiary_address_line2: String?

        def beneficiary_address_line2=: (String) -> String

        attr_reader beneficiary_address_line3: String?

        def beneficiary_address_line3=: (String) -> String

        attr_reader beneficiary_name: String?

        def beneficiary_name=: (String) -> String

        attr_reader originator_address_line1: String?

        def originator_address_line1=: (String) -> String

        attr_reader originator_address_line2: String?

        def originator_address_line2=: (String) -> String

        attr_reader originator_address_line3: String?

        def originator_address_line3=: (String) -> String

        attr_reader originator_name: String?

        def originator_name=: (String) -> String

        attr_reader originator_to_beneficiary_information_line1: String?

        def originator_to_beneficiary_information_line1=: (String) -> String

        attr_reader originator_to_beneficiary_information_line2: String?

        def originator_to_beneficiary_information_line2=: (String) -> String

        attr_reader originator_to_beneficiary_information_line3: String?

        def originator_to_beneficiary_information_line3=: (String) -> String

        attr_reader originator_to_beneficiary_information_line4: String?

        def originator_to_beneficiary_information_line4=: (String) -> String

        def initialize: (
          amount: Integer,
          beneficiary_account_number: String,
          beneficiary_routing_number: String,
          currency: String,
          message_to_recipient: String,
          originator_account_number: String,
          originator_routing_number: String,
          recipient_account_number_id: String,
          ?beneficiary_address_line1: String,
          ?beneficiary_address_line2: String,
          ?beneficiary_address_line3: String,
          ?beneficiary_name: String,
          ?originator_address_line1: String,
          ?originator_address_line2: String,
          ?originator_address_line3: String,
          ?originator_name: String,
          ?originator_to_beneficiary_information_line1: String,
          ?originator_to_beneficiary_information_line2: String,
          ?originator_to_beneficiary_information_line3: String,
          ?originator_to_beneficiary_information_line4: String,
          ?request_options: Increase::request_opts
        ) -> void

        def to_hash: -> Increase::Models::Simulations::inbound_wire_drawdown_request_create_params
      end
    end
  end
end
