module Increase
  module Models
    module Simulations
      type inbound_mail_item_create_params =
        { amount: Integer, lockbox_id: String, contents_file_id: String }
        & Increase::Internal::Type::request_parameters

      class InboundMailItemCreateParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor amount: Integer

        attr_accessor lockbox_id: String

        attr_reader contents_file_id: String?

        def contents_file_id=: (String) -> String

        def initialize: (
          amount: Integer,
          lockbox_id: String,
          ?contents_file_id: String,
          ?request_options: Increase::request_opts
        ) -> void

        def to_hash: -> Increase::Models::Simulations::inbound_mail_item_create_params
      end
    end
  end
end
