module Increase
  module Models
    module Simulations
      type inbound_ach_transfer_create_params =
        {
          account_number_id: String,
          amount: Integer,
          company_descriptive_date: String,
          company_discretionary_data: String,
          company_entry_description: String,
          company_id: String,
          company_name: String,
          receiver_id_number: String,
          receiver_name: String,
          resolve_at: Time,
          standard_entry_class_code: Increase::Models::Simulations::InboundACHTransferCreateParams::standard_entry_class_code
        }
        & Increase::Internal::Type::request_parameters

      class InboundACHTransferCreateParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor account_number_id: String

        attr_accessor amount: Integer

        attr_reader company_descriptive_date: String?

        def company_descriptive_date=: (String) -> String

        attr_reader company_discretionary_data: String?

        def company_discretionary_data=: (String) -> String

        attr_reader company_entry_description: String?

        def company_entry_description=: (String) -> String

        attr_reader company_id: String?

        def company_id=: (String) -> String

        attr_reader company_name: String?

        def company_name=: (String) -> String

        attr_reader receiver_id_number: String?

        def receiver_id_number=: (String) -> String

        attr_reader receiver_name: String?

        def receiver_name=: (String) -> String

        attr_reader resolve_at: Time?

        def resolve_at=: (Time) -> Time

        attr_reader standard_entry_class_code: Increase::Models::Simulations::InboundACHTransferCreateParams::standard_entry_class_code?

        def standard_entry_class_code=: (
          Increase::Models::Simulations::InboundACHTransferCreateParams::standard_entry_class_code
        ) -> Increase::Models::Simulations::InboundACHTransferCreateParams::standard_entry_class_code

        def initialize: (
          account_number_id: String,
          amount: Integer,
          ?company_descriptive_date: String,
          ?company_discretionary_data: String,
          ?company_entry_description: String,
          ?company_id: String,
          ?company_name: String,
          ?receiver_id_number: String,
          ?receiver_name: String,
          ?resolve_at: Time,
          ?standard_entry_class_code: Increase::Models::Simulations::InboundACHTransferCreateParams::standard_entry_class_code,
          ?request_options: Increase::request_opts
        ) -> void

        type standard_entry_class_code =
          :corporate_credit_or_debit
          | :corporate_trade_exchange
          | :prearranged_payments_and_deposit
          | :internet_initiated
          | :point_of_sale
          | :telephone_initiated
          | :customer_initiated
          | :accounts_receivable
          | :machine_transfer
          | :shared_network_transaction
          | :represented_check
          | :back_office_conversion
          | :point_of_purchase
          | :check_truncation
          | :destroyed_check
          | :international_ach_transaction

        module StandardEntryClassCode
          extend Increase::Internal::Type::Enum

          # Corporate Credit and Debit (CCD).
          CORPORATE_CREDIT_OR_DEBIT: :corporate_credit_or_debit

          # Corporate Trade Exchange (CTX).
          CORPORATE_TRADE_EXCHANGE: :corporate_trade_exchange

          # Prearranged Payments and Deposits (PPD).
          PREARRANGED_PAYMENTS_AND_DEPOSIT: :prearranged_payments_and_deposit

          # Internet Initiated (WEB).
          INTERNET_INITIATED: :internet_initiated

          # Point of Sale (POS).
          POINT_OF_SALE: :point_of_sale

          # Telephone Initiated (TEL).
          TELEPHONE_INITIATED: :telephone_initiated

          # Customer Initiated (CIE).
          CUSTOMER_INITIATED: :customer_initiated

          # Accounts Receivable (ARC).
          ACCOUNTS_RECEIVABLE: :accounts_receivable

          # Machine Transfer (MTE).
          MACHINE_TRANSFER: :machine_transfer

          # Shared Network Transaction (SHR).
          SHARED_NETWORK_TRANSACTION: :shared_network_transaction

          # Represented Check (RCK).
          REPRESENTED_CHECK: :represented_check

          # Back Office Conversion (BOC).
          BACK_OFFICE_CONVERSION: :back_office_conversion

          # Point of Purchase (POP).
          POINT_OF_PURCHASE: :point_of_purchase

          # Check Truncation (TRC).
          CHECK_TRUNCATION: :check_truncation

          # Destroyed Check (XCK).
          DESTROYED_CHECK: :destroyed_check

          # International ACH Transaction (IAT).
          INTERNATIONAL_ACH_TRANSACTION: :international_ach_transaction

          def self?.values: -> ::Array[Increase::Models::Simulations::InboundACHTransferCreateParams::standard_entry_class_code]
        end
      end
    end
  end
end
