module Increase
  module Models
    module Simulations
      type inbound_check_deposit_create_params =
        { account_number_id: String, amount: Integer, check_number: String }
        & Increase::Internal::Type::request_parameters

      class InboundCheckDepositCreateParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor account_number_id: String

        attr_accessor amount: Integer

        attr_accessor check_number: String

        def initialize: (
          account_number_id: String,
          amount: Integer,
          check_number: String,
          ?request_options: Increase::request_opts
        ) -> void

        def to_hash: -> Increase::Models::Simulations::inbound_check_deposit_create_params
      end
    end
  end
end
