module Increase
  module Models
    module Simulations
      type program_create_params =
        { name: String } & Increase::Internal::Type::request_parameters

      class ProgramCreateParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor name: String

        def initialize: (
          name: String,
          ?request_options: Increase::request_opts
        ) -> void

        def to_hash: -> Increase::Models::Simulations::program_create_params
      end
    end
  end
end
