module Increase
  module Models
    module Simulations
      type program_create_params =
        { name: String, reserve_account_id: String }
        & Increase::Internal::Type::request_parameters

      class ProgramCreateParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        attr_accessor name: String

        attr_reader reserve_account_id: String?

        def reserve_account_id=: (String) -> String

        def initialize: (
          name: String,
          ?reserve_account_id: String,
          ?request_options: Increase::request_opts
        ) -> void
      end
    end
  end
end
