module Increase
  module Models
    module Simulations
      type wire_transfer_reverse_params =
        {  } & Increase::Internal::Type::request_parameters

      class WireTransferReverseParams < Increase::Internal::Type::BaseModel
        extend Increase::Internal::Type::RequestParameters::Converter
        include Increase::Internal::Type::RequestParameters

        def initialize: (?request_options: Increase::request_opts) -> void
      end
    end
  end
end
