# frozen_string_literal: true

module Increase
  module Models
    class File < BaseModel
      # @!attribute [rw] id
      #   The File's identifier.
      #   @return [String]
      required :id, String

      # @!attribute [rw] created_at
      #   The time the File was created.
      #   @return [Time]
      required :created_at, Time

      # @!attribute [rw] description
      #   A description of the File.
      #   @return [String]
      required :description, String

      # @!attribute [rw] direction
      #   Whether the File was generated by Increase or by you and sent to Increase.
      #   @return [Symbol, Increase::Models::File::Direction]
      required :direction, enum: -> { Increase::Models::File::Direction }

      # @!attribute [rw] download_url
      #   A URL from where the File can be downloaded at this point in time. The location of this URL may change over time.
      #   @return [String]
      required :download_url, String

      # @!attribute [rw] filename
      #   The filename that was provided upon upload or generated by Increase.
      #   @return [String]
      required :filename, String

      # @!attribute [rw] idempotency_key
      #   The idempotency key you chose for this object. This value is unique across Increase and is used to ensure that a request is only processed once. Learn more about [idempotency](https://increase.com/documentation/idempotency-keys).
      #   @return [String]
      required :idempotency_key, String

      # @!attribute [rw] mime_type
      #   The MIME type of the file.
      #   @return [String]
      required :mime_type, String

      # @!attribute [rw] purpose
      #   What the File will be used for. We may add additional possible values for this enum over time; your application should be able to handle such additions gracefully.
      #   @return [Symbol, Increase::Models::File::Purpose]
      required :purpose, enum: -> { Increase::Models::File::Purpose }

      # @!attribute [rw] type
      #   A constant representing the object's type. For this resource it will always be `file`.
      #   @return [Symbol, Increase::Models::File::Type]
      required :type, enum: -> { Increase::Models::File::Type }

      # Whether the File was generated by Increase or by you and sent to Increase.
      class Direction < Increase::Enum
        # This File was sent by you to Increase.
        TO_INCREASE = :to_increase

        # This File was generated by Increase.
        FROM_INCREASE = :from_increase
      end

      # What the File will be used for. We may add additional possible values for this enum over time; your application should be able to handle such additions gracefully.
      class Purpose < Increase::Enum
        # An image of the front of a check, used for check deposits.
        CHECK_IMAGE_FRONT = :check_image_front

        # An image of the back of a check, used for check deposits.
        CHECK_IMAGE_BACK = :check_image_back

        # An image of the front of a deposited check after processing by Increase and submission to the Federal Reserve.
        PROCESSED_CHECK_IMAGE_FRONT = :processed_check_image_front

        # An image of the back of a deposited check after processing by Increase and submission to the Federal Reserve.
        PROCESSED_CHECK_IMAGE_BACK = :processed_check_image_back

        # An image of a check that was mailed to a recipient.
        MAILED_CHECK_IMAGE = :mailed_check_image

        # A scanned mail item sent to Increase.
        INBOUND_MAIL_ITEM = :inbound_mail_item

        # IRS Form 1099-INT.
        FORM_1099_INT = :form_1099_int

        # IRS Form SS-4.
        FORM_SS_4 = :form_ss_4

        # An image of a government-issued ID.
        IDENTITY_DOCUMENT = :identity_document

        # A statement generated by Increase.
        INCREASE_STATEMENT = :increase_statement

        # A file purpose not covered by any of the other cases.
        OTHER = :other

        # A legal document forming a trust.
        TRUST_FORMATION_DOCUMENT = :trust_formation_document

        # A card image to be rendered inside digital wallet apps. This must be a 1536x969 pixel PNG.
        DIGITAL_WALLET_ARTWORK = :digital_wallet_artwork

        # An icon for you app to be rendered inside digital wallet apps. This must be a 100x100 pixel PNG.
        DIGITAL_WALLET_APP_ICON = :digital_wallet_app_icon

        # A card image to be printed on the front of a physical card. This must be a 2100x1340 pixel PNG with no other color but black.
        PHYSICAL_CARD_FRONT = :physical_card_front

        # The image to be printed on the back of a physical card.
        PHYSICAL_CARD_BACK = :physical_card_back

        # An image representing the entirety of the carrier used for a physical card. This must be a 2550x3300 pixel PNG with no other color but black.
        PHYSICAL_CARD_CARRIER = :physical_card_carrier

        # A document requested by Increase.
        DOCUMENT_REQUEST = :document_request

        # A supplemental document associated an an Entity.
        ENTITY_SUPPLEMENTAL_DOCUMENT = :entity_supplemental_document

        # The results of an Export you requested via the dashboard or API.
        EXPORT = :export

        # An attachment to an Unusual Activity Report.
        UNUSUAL_ACTIVITY_REPORT_ATTACHMENT = :unusual_activity_report_attachment

        # A document granting another entity access to the funds into your account.
        DEPOSIT_ACCOUNT_CONTROL_AGREEMENT = :deposit_account_control_agreement
      end

      # A constant representing the object's type. For this resource it will always be `file`.
      class Type < Increase::Enum
        FILE = :file
      end

      # Create a new instance of File from a Hash of raw data.
      #
      # @overload initialize(id: nil, created_at: nil, description: nil, direction: nil, download_url: nil, filename: nil, idempotency_key: nil, mime_type: nil, purpose: nil, type: nil)
      # @param id [String] The File's identifier.
      # @param created_at [String] The time the File was created.
      # @param description [String] A description of the File.
      # @param direction [String] Whether the File was generated by Increase or by you and sent to Increase.
      # @param download_url [String] A URL from where the File can be downloaded at this point in time. The location
      #   of this URL may change over time.
      # @param filename [String] The filename that was provided upon upload or generated by Increase.
      # @param idempotency_key [String] The idempotency key you chose for this object. This value is unique across
      #   Increase and is used to ensure that a request is only processed once. Learn more
      #   about [idempotency](https://increase.com/documentation/idempotency-keys).
      # @param mime_type [String] The MIME type of the file.
      # @param purpose [String] What the File will be used for. We may add additional possible values for this
      #   enum over time; your application should be able to handle such additions
      #   gracefully.
      # @param type [String] A constant representing the object's type. For this resource it will always be
      #   `file`.
      def initialize(data = {})
        super
      end
    end
  end
end
