# typed: strong

module Increase
  module Models
    class File < Increase::BaseModel
      # The File's identifier.
      sig { returns(String) }
      def id
      end

      sig { params(_: String).returns(String) }
      def id=(_)
      end

      # The time the File was created.
      sig { returns(Time) }
      def created_at
      end

      sig { params(_: Time).returns(Time) }
      def created_at=(_)
      end

      # A description of the File.
      sig { returns(T.nilable(String)) }
      def description
      end

      sig { params(_: T.nilable(String)).returns(T.nilable(String)) }
      def description=(_)
      end

      # Whether the File was generated by Increase or by you and sent to Increase.
      sig { returns(Symbol) }
      def direction
      end

      sig { params(_: Symbol).returns(Symbol) }
      def direction=(_)
      end

      # A URL from where the File can be downloaded at this point in time. The location
      #   of this URL may change over time.
      sig { returns(T.nilable(String)) }
      def download_url
      end

      sig { params(_: T.nilable(String)).returns(T.nilable(String)) }
      def download_url=(_)
      end

      # The filename that was provided upon upload or generated by Increase.
      sig { returns(T.nilable(String)) }
      def filename
      end

      sig { params(_: T.nilable(String)).returns(T.nilable(String)) }
      def filename=(_)
      end

      # The idempotency key you chose for this object. This value is unique across
      #   Increase and is used to ensure that a request is only processed once. Learn more
      #   about [idempotency](https://increase.com/documentation/idempotency-keys).
      sig { returns(T.nilable(String)) }
      def idempotency_key
      end

      sig { params(_: T.nilable(String)).returns(T.nilable(String)) }
      def idempotency_key=(_)
      end

      # The MIME type of the file.
      sig { returns(String) }
      def mime_type
      end

      sig { params(_: String).returns(String) }
      def mime_type=(_)
      end

      # What the File will be used for. We may add additional possible values for this
      #   enum over time; your application should be able to handle such additions
      #   gracefully.
      sig { returns(Symbol) }
      def purpose
      end

      sig { params(_: Symbol).returns(Symbol) }
      def purpose=(_)
      end

      # A constant representing the object's type. For this resource it will always be
      #   `file`.
      sig { returns(Symbol) }
      def type
      end

      sig { params(_: Symbol).returns(Symbol) }
      def type=(_)
      end

      # Files are objects that represent a file hosted on Increase's servers. The file
      #   may have been uploaded by you (for example, when uploading a check image) or it
      #   may have been created by Increase (for example, an autogenerated statement PDF).
      sig do
        params(
          id: String,
          created_at: Time,
          description: T.nilable(String),
          direction: Symbol,
          download_url: T.nilable(String),
          filename: T.nilable(String),
          idempotency_key: T.nilable(String),
          mime_type: String,
          purpose: Symbol,
          type: Symbol
        )
          .returns(T.attached_class)
      end
      def self.new(
        id:,
        created_at:,
        description:,
        direction:,
        download_url:,
        filename:,
        idempotency_key:,
        mime_type:,
        purpose:,
        type:
      )
      end

      sig do
        override
          .returns(
            {
              id: String,
              created_at: Time,
              description: T.nilable(String),
              direction: Symbol,
              download_url: T.nilable(String),
              filename: T.nilable(String),
              idempotency_key: T.nilable(String),
              mime_type: String,
              purpose: Symbol,
              type: Symbol
            }
          )
      end
      def to_hash
      end

      # Whether the File was generated by Increase or by you and sent to Increase.
      class Direction < Increase::Enum
        abstract!

        # This File was sent by you to Increase.
        TO_INCREASE = :to_increase

        # This File was generated by Increase.
        FROM_INCREASE = :from_increase

        class << self
          sig { override.returns(T::Array[Symbol]) }
          def values
          end
        end
      end

      # What the File will be used for. We may add additional possible values for this
      #   enum over time; your application should be able to handle such additions
      #   gracefully.
      class Purpose < Increase::Enum
        abstract!

        # An image of the front of a check, used for check deposits.
        CHECK_IMAGE_FRONT = :check_image_front

        # An image of the back of a check, used for check deposits.
        CHECK_IMAGE_BACK = :check_image_back

        # An image of the front of a deposited check after processing by Increase and submission to the Federal Reserve.
        PROCESSED_CHECK_IMAGE_FRONT = :processed_check_image_front

        # An image of the back of a deposited check after processing by Increase and submission to the Federal Reserve.
        PROCESSED_CHECK_IMAGE_BACK = :processed_check_image_back

        # An image of a check that was mailed to a recipient.
        MAILED_CHECK_IMAGE = :mailed_check_image

        # An image to be printed on the bottom or voucher of a check that you've requested Increase print.
        CHECK_VOUCHER_IMAGE = :check_voucher_image

        # An image to be printed on an additional page and mailed with a check that you've requested Increase print.
        CHECK_ATTACHMENT_IMAGE = :check_attachment_image

        # A scanned mail item sent to Increase.
        INBOUND_MAIL_ITEM = :inbound_mail_item

        # IRS Form 1099-INT.
        FORM_1099_INT = :form_1099_int

        # IRS Form 1099-MISC.
        FORM_1099_MISC = :form_1099_misc

        # IRS Form SS-4.
        FORM_SS_4 = :form_ss_4

        # An image of a government-issued ID.
        IDENTITY_DOCUMENT = :identity_document

        # A statement generated by Increase.
        INCREASE_STATEMENT = :increase_statement

        # A file purpose not covered by any of the other cases.
        OTHER = :other

        # A legal document forming a trust.
        TRUST_FORMATION_DOCUMENT = :trust_formation_document

        # A card image to be rendered inside digital wallet apps. This must be a 1536x969 pixel PNG.
        DIGITAL_WALLET_ARTWORK = :digital_wallet_artwork

        # An icon for you app to be rendered inside digital wallet apps. This must be a 100x100 pixel PNG.
        DIGITAL_WALLET_APP_ICON = :digital_wallet_app_icon

        # A card image to be printed on the front of a physical card. This must be a 2100x1340 pixel PNG with no other color but black.
        PHYSICAL_CARD_FRONT = :physical_card_front

        # The image to be printed on the back of a physical card.
        PHYSICAL_CARD_BACK = :physical_card_back

        # An image representing the entirety of the carrier used for a physical card. This must be a 2550x3300 pixel PNG with no other color but black.
        PHYSICAL_CARD_CARRIER = :physical_card_carrier

        # A document requested by Increase.
        DOCUMENT_REQUEST = :document_request

        # A supplemental document associated an an Entity.
        ENTITY_SUPPLEMENTAL_DOCUMENT = :entity_supplemental_document

        # The results of an Export you requested via the dashboard or API.
        EXPORT = :export

        # An attachment to an Unusual Activity Report.
        UNUSUAL_ACTIVITY_REPORT_ATTACHMENT = :unusual_activity_report_attachment

        # A document granting another entity access to the funds into your account.
        DEPOSIT_ACCOUNT_CONTROL_AGREEMENT = :deposit_account_control_agreement

        # A file containing additional evidence for a Proof of Authorization Request Submission.
        PROOF_OF_AUTHORIZATION_REQUEST_SUBMISSION = :proof_of_authorization_request_submission

        class << self
          sig { override.returns(T::Array[Symbol]) }
          def values
          end
        end
      end

      # A constant representing the object's type. For this resource it will always be
      #   `file`.
      class Type < Increase::Enum
        abstract!

        FILE = :file

        class << self
          sig { override.returns(T::Array[Symbol]) }
          def values
          end
        end
      end
    end
  end
end
