#!/usr/bin/env bash

set -Eeuo pipefail

cd -- "$(dirname -- "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check > /dev/null 2>&1 || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

echo "==> Installing Ruby dependencies…"

BUNDLE_FROZEN=1 exec -- bundle install "$@"
